package com.daniloaraujosilva.mathemagika.library.jvm.functions

import com.daniloaraujosilva.mathemagika.library.jvm.common.MathematicaFunction

/**
 *````
 *
 *                   AdobeStandard
 *                   ASCII
 *                   CP936
 *                   CP949
 *                   CP950
 *                   Custom
 *                   EUC-JP
 *                   EUC
 *                   IBM-850
 *                   ISO8859-10
 *                   ISO8859-11
 *                   ISO8859-13
 *                   ISO8859-14
 *                   ISO8859-15
 *                   ISO8859-16
 *                   ISO8859-1
 *                   ISO8859-2
 *                   ISO8859-3
 *                   ISO8859-4
 *                   ISO8859-5
 *                   ISO8859-6
 *                   ISO8859-7
 *                   ISO8859-8
 *                   ISO8859-9
 *                   ISOLatin1
 *                   ISOLatin2
 *                   ISOLatin3
 *                   ISOLatin4
 *                   ISOLatinCyrillic
 *                   Klingon
 *                   koi8-r
 *                   MacintoshArabic
 *                   MacintoshChineseSimplified
 *                   MacintoshChineseTraditional
 *                   MacintoshCroatian
 *                   MacintoshCyrillic
 *                   MacintoshGreek
 *                   MacintoshHebrew
 *                   MacintoshIcelandic
 *                   MacintoshKorean
 *                   MacintoshNonCyrillicSlavic
 *                   MacintoshRomanian
 *                   MacintoshRoman
 *                   MacintoshRomanPDFExport
 *                   MacintoshThai
 *                   MacintoshTurkish
 *                   MacintoshUkrainian
 *                   Math1
 *                   Math2
 *                   Math3
 *                   Math4
 *                   Math5
 *                   Mathematica1
 *                   Mathematica2
 *                   Mathematica3
 *                   Mathematica4
 *                   Mathematica5
 *                   Mathematica6
 *                   Mathematica7
 *                   PrintableASCII
 *                   ShiftJIS
 *                   Symbol
 *                   UTF-8
 *                   UTF8
 *                   WindowsANSI
 *                   WindowsBaltic
 *                   WindowsCyrillic
 *                   WindowsEastEurope
 *                   WindowsGreek
 *                   WindowsThai
 *                   WindowsTurkish
 * Name:             ZapfDingbats
 *
 *                   Missing[UnknownSymbol, AdobeStandard][FullName]
 *                   Missing[UnknownSymbol, ASCII][FullName]
 *                   Missing[UnknownSymbol, CP936][FullName]
 *                   Missing[UnknownSymbol, CP949][FullName]
 *                   Missing[UnknownSymbol, CP950][FullName]
 *                   Missing[UnknownSymbol, Custom][FullName]
 *                   Missing[UnknownSymbol, EUC-JP][FullName]
 *                   Missing[UnknownSymbol, EUC][FullName]
 *                   Missing[UnknownSymbol, IBM-850][FullName]
 *                   Missing[UnknownSymbol, ISO8859-10][FullName]
 *                   Missing[UnknownSymbol, ISO8859-11][FullName]
 *                   Missing[UnknownSymbol, ISO8859-13][FullName]
 *                   Missing[UnknownSymbol, ISO8859-14][FullName]
 *                   Missing[UnknownSymbol, ISO8859-15][FullName]
 *                   Missing[UnknownSymbol, ISO8859-16][FullName]
 *                   Missing[UnknownSymbol, ISO8859-1][FullName]
 *                   Missing[UnknownSymbol, ISO8859-2][FullName]
 *                   Missing[UnknownSymbol, ISO8859-3][FullName]
 *                   Missing[UnknownSymbol, ISO8859-4][FullName]
 *                   Missing[UnknownSymbol, ISO8859-5][FullName]
 *                   Missing[UnknownSymbol, ISO8859-6][FullName]
 *                   Missing[UnknownSymbol, ISO8859-7][FullName]
 *                   Missing[UnknownSymbol, ISO8859-8][FullName]
 *                   Missing[UnknownSymbol, ISO8859-9][FullName]
 *                   Missing[UnknownSymbol, ISOLatin1][FullName]
 *                   Missing[UnknownSymbol, ISOLatin2][FullName]
 *                   Missing[UnknownSymbol, ISOLatin3][FullName]
 *                   Missing[UnknownSymbol, ISOLatin4][FullName]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][FullName]
 *                   Missing[UnknownSymbol, Klingon][FullName]
 *                   Missing[UnknownSymbol, koi8-r][FullName]
 *                   Missing[UnknownSymbol, MacintoshArabic][FullName]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][FullName]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][FullName]
 *                   Missing[UnknownSymbol, MacintoshCroatian][FullName]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][FullName]
 *                   Missing[UnknownSymbol, MacintoshGreek][FullName]
 *                   Missing[UnknownSymbol, MacintoshHebrew][FullName]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][FullName]
 *                   Missing[UnknownSymbol, MacintoshKorean][FullName]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][FullName]
 *                   Missing[UnknownSymbol, MacintoshRomanian][FullName]
 *                   Missing[UnknownSymbol, MacintoshRoman][FullName]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][FullName]
 *                   Missing[UnknownSymbol, MacintoshThai][FullName]
 *                   Missing[UnknownSymbol, MacintoshTurkish][FullName]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][FullName]
 *                   Missing[UnknownSymbol, Math1][FullName]
 *                   Missing[UnknownSymbol, Math2][FullName]
 *                   Missing[UnknownSymbol, Math3][FullName]
 *                   Missing[UnknownSymbol, Math4][FullName]
 *                   Missing[UnknownSymbol, Math5][FullName]
 *                   Missing[UnknownSymbol, Mathematica1][FullName]
 *                   Missing[UnknownSymbol, Mathematica2][FullName]
 *                   Missing[UnknownSymbol, Mathematica3][FullName]
 *                   Missing[UnknownSymbol, Mathematica4][FullName]
 *                   Missing[UnknownSymbol, Mathematica5][FullName]
 *                   Missing[UnknownSymbol, Mathematica6][FullName]
 *                   Missing[UnknownSymbol, Mathematica7][FullName]
 *                   Missing[UnknownSymbol, PrintableASCII][FullName]
 *                   Missing[UnknownSymbol, ShiftJIS][FullName]
 *                   System`Symbol
 *                   Missing[UnknownSymbol, UTF-8][FullName]
 *                   Missing[UnknownSymbol, UTF8][FullName]
 *                   Missing[UnknownSymbol, WindowsANSI][FullName]
 *                   Missing[UnknownSymbol, WindowsBaltic][FullName]
 *                   Missing[UnknownSymbol, WindowsCyrillic][FullName]
 *                   Missing[UnknownSymbol, WindowsEastEurope][FullName]
 *                   Missing[UnknownSymbol, WindowsGreek][FullName]
 *                   Missing[UnknownSymbol, WindowsThai][FullName]
 *                   Missing[UnknownSymbol, WindowsTurkish][FullName]
 * Full name:        Missing[UnknownSymbol, ZapfDingbats][FullName]
 *
 * Usage:            {Missing[UnknownSymbol, AdobeStandard][Usage], Missing[UnknownSymbol, ASCII][Usage], Missing[UnknownSymbol, CP936][Usage], Missing[UnknownSymbol, CP949][Usage], Missing[UnknownSymbol, CP950][Usage], Missing[UnknownSymbol, Custom][Usage], Missing[UnknownSymbol, EUC-JP][Usage], Missing[UnknownSymbol, EUC][Usage], Missing[UnknownSymbol, IBM-850][Usage], Missing[UnknownSymbol, ISO8859-10][Usage], Missing[UnknownSymbol, ISO8859-11][Usage], Missing[UnknownSymbol, ISO8859-13][Usage], Missing[UnknownSymbol, ISO8859-14][Usage], Missing[UnknownSymbol, ISO8859-15][Usage], Missing[UnknownSymbol, ISO8859-16][Usage], Missing[UnknownSymbol, ISO8859-1][Usage], Missing[UnknownSymbol, ISO8859-2][Usage], Missing[UnknownSymbol, ISO8859-3][Usage], Missing[UnknownSymbol, ISO8859-4][Usage], Missing[UnknownSymbol, ISO8859-5][Usage], Missing[UnknownSymbol, ISO8859-6][Usage], Missing[UnknownSymbol, ISO8859-7][Usage], Missing[UnknownSymbol, ISO8859-8][Usage], Missing[UnknownSymbol, ISO8859-9][Usage], Missing[UnknownSymbol, ISOLatin1][Usage], Missing[UnknownSymbol, ISOLatin2][Usage], Missing[UnknownSymbol, ISOLatin3][Usage], Missing[UnknownSymbol, ISOLatin4][Usage], Missing[UnknownSymbol, ISOLatinCyrillic][Usage], Missing[UnknownSymbol, Klingon][Usage], Missing[UnknownSymbol, koi8-r][Usage], Missing[UnknownSymbol, MacintoshArabic][Usage], Missing[UnknownSymbol, MacintoshChineseSimplified][Usage], Missing[UnknownSymbol, MacintoshChineseTraditional][Usage], Missing[UnknownSymbol, MacintoshCroatian][Usage], Missing[UnknownSymbol, MacintoshCyrillic][Usage], Missing[UnknownSymbol, MacintoshGreek][Usage], Missing[UnknownSymbol, MacintoshHebrew][Usage], Missing[UnknownSymbol, MacintoshIcelandic][Usage], Missing[UnknownSymbol, MacintoshKorean][Usage], Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][Usage], Missing[UnknownSymbol, MacintoshRomanian][Usage], Missing[UnknownSymbol, MacintoshRoman][Usage], Missing[UnknownSymbol, MacintoshRomanPDFExport][Usage], Missing[UnknownSymbol, MacintoshThai][Usage], Missing[UnknownSymbol, MacintoshTurkish][Usage], Missing[UnknownSymbol, MacintoshUkrainian][Usage], Missing[UnknownSymbol, Math1][Usage], Missing[UnknownSymbol, Math2][Usage], Missing[UnknownSymbol, Math3][Usage], Missing[UnknownSymbol, Math4][Usage], Missing[UnknownSymbol, Math5][Usage], Missing[UnknownSymbol, Mathematica1][Usage], Missing[UnknownSymbol, Mathematica2][Usage], Missing[UnknownSymbol, Mathematica3][Usage], Missing[UnknownSymbol, Mathematica4][Usage], Missing[UnknownSymbol, Mathematica5][Usage], Missing[UnknownSymbol, Mathematica6][Usage], Missing[UnknownSymbol, Mathematica7][Usage], Missing[UnknownSymbol, PrintableASCII][Usage], Missing[UnknownSymbol, ShiftJIS][Usage], Symbol["name"] refers to a symbol with the specified name. , Missing[UnknownSymbol, UTF-8][Usage], Missing[UnknownSymbol, UTF8][Usage], Missing[UnknownSymbol, WindowsANSI][Usage], Missing[UnknownSymbol, WindowsBaltic][Usage], Missing[UnknownSymbol, WindowsCyrillic][Usage], Missing[UnknownSymbol, WindowsEastEurope][Usage], Missing[UnknownSymbol, WindowsGreek][Usage], Missing[UnknownSymbol, WindowsThai][Usage], Missing[UnknownSymbol, WindowsTurkish][Usage], Missing[UnknownSymbol, ZapfDingbats][Usage]}
 *
 *                   Missing[UnknownSymbol, AdobeStandard][Options]
 *                   Missing[UnknownSymbol, ASCII][Options]
 *                   Missing[UnknownSymbol, CP936][Options]
 *                   Missing[UnknownSymbol, CP949][Options]
 *                   Missing[UnknownSymbol, CP950][Options]
 *                   Missing[UnknownSymbol, Custom][Options]
 *                   Missing[UnknownSymbol, EUC-JP][Options]
 *                   Missing[UnknownSymbol, EUC][Options]
 *                   Missing[UnknownSymbol, IBM-850][Options]
 *                   Missing[UnknownSymbol, ISO8859-10][Options]
 *                   Missing[UnknownSymbol, ISO8859-11][Options]
 *                   Missing[UnknownSymbol, ISO8859-13][Options]
 *                   Missing[UnknownSymbol, ISO8859-14][Options]
 *                   Missing[UnknownSymbol, ISO8859-15][Options]
 *                   Missing[UnknownSymbol, ISO8859-16][Options]
 *                   Missing[UnknownSymbol, ISO8859-1][Options]
 *                   Missing[UnknownSymbol, ISO8859-2][Options]
 *                   Missing[UnknownSymbol, ISO8859-3][Options]
 *                   Missing[UnknownSymbol, ISO8859-4][Options]
 *                   Missing[UnknownSymbol, ISO8859-5][Options]
 *                   Missing[UnknownSymbol, ISO8859-6][Options]
 *                   Missing[UnknownSymbol, ISO8859-7][Options]
 *                   Missing[UnknownSymbol, ISO8859-8][Options]
 *                   Missing[UnknownSymbol, ISO8859-9][Options]
 *                   Missing[UnknownSymbol, ISOLatin1][Options]
 *                   Missing[UnknownSymbol, ISOLatin2][Options]
 *                   Missing[UnknownSymbol, ISOLatin3][Options]
 *                   Missing[UnknownSymbol, ISOLatin4][Options]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][Options]
 *                   Missing[UnknownSymbol, Klingon][Options]
 *                   Missing[UnknownSymbol, koi8-r][Options]
 *                   Missing[UnknownSymbol, MacintoshArabic][Options]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][Options]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][Options]
 *                   Missing[UnknownSymbol, MacintoshCroatian][Options]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][Options]
 *                   Missing[UnknownSymbol, MacintoshGreek][Options]
 *                   Missing[UnknownSymbol, MacintoshHebrew][Options]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][Options]
 *                   Missing[UnknownSymbol, MacintoshKorean][Options]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][Options]
 *                   Missing[UnknownSymbol, MacintoshRomanian][Options]
 *                   Missing[UnknownSymbol, MacintoshRoman][Options]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][Options]
 *                   Missing[UnknownSymbol, MacintoshThai][Options]
 *                   Missing[UnknownSymbol, MacintoshTurkish][Options]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][Options]
 *                   Missing[UnknownSymbol, Math1][Options]
 *                   Missing[UnknownSymbol, Math2][Options]
 *                   Missing[UnknownSymbol, Math3][Options]
 *                   Missing[UnknownSymbol, Math4][Options]
 *                   Missing[UnknownSymbol, Math5][Options]
 *                   Missing[UnknownSymbol, Mathematica1][Options]
 *                   Missing[UnknownSymbol, Mathematica2][Options]
 *                   Missing[UnknownSymbol, Mathematica3][Options]
 *                   Missing[UnknownSymbol, Mathematica4][Options]
 *                   Missing[UnknownSymbol, Mathematica5][Options]
 *                   Missing[UnknownSymbol, Mathematica6][Options]
 *                   Missing[UnknownSymbol, Mathematica7][Options]
 *                   Missing[UnknownSymbol, PrintableASCII][Options]
 *                   Missing[UnknownSymbol, ShiftJIS][Options]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][Options]
 *                   Missing[UnknownSymbol, UTF8][Options]
 *                   Missing[UnknownSymbol, WindowsANSI][Options]
 *                   Missing[UnknownSymbol, WindowsBaltic][Options]
 *                   Missing[UnknownSymbol, WindowsCyrillic][Options]
 *                   Missing[UnknownSymbol, WindowsEastEurope][Options]
 *                   Missing[UnknownSymbol, WindowsGreek][Options]
 *                   Missing[UnknownSymbol, WindowsThai][Options]
 *                   Missing[UnknownSymbol, WindowsTurkish][Options]
 * Options:          Missing[UnknownSymbol, ZapfDingbats][Options]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][Attributes]
 *                   Missing[UnknownSymbol, ASCII][Attributes]
 *                   Missing[UnknownSymbol, CP936][Attributes]
 *                   Missing[UnknownSymbol, CP949][Attributes]
 *                   Missing[UnknownSymbol, CP950][Attributes]
 *                   Missing[UnknownSymbol, Custom][Attributes]
 *                   Missing[UnknownSymbol, EUC-JP][Attributes]
 *                   Missing[UnknownSymbol, EUC][Attributes]
 *                   Missing[UnknownSymbol, IBM-850][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-10][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-11][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-13][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-14][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-15][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-16][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-1][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-2][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-3][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-4][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-5][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-6][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-7][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-8][Attributes]
 *                   Missing[UnknownSymbol, ISO8859-9][Attributes]
 *                   Missing[UnknownSymbol, ISOLatin1][Attributes]
 *                   Missing[UnknownSymbol, ISOLatin2][Attributes]
 *                   Missing[UnknownSymbol, ISOLatin3][Attributes]
 *                   Missing[UnknownSymbol, ISOLatin4][Attributes]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][Attributes]
 *                   Missing[UnknownSymbol, Klingon][Attributes]
 *                   Missing[UnknownSymbol, koi8-r][Attributes]
 *                   Missing[UnknownSymbol, MacintoshArabic][Attributes]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][Attributes]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][Attributes]
 *                   Missing[UnknownSymbol, MacintoshCroatian][Attributes]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][Attributes]
 *                   Missing[UnknownSymbol, MacintoshGreek][Attributes]
 *                   Missing[UnknownSymbol, MacintoshHebrew][Attributes]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][Attributes]
 *                   Missing[UnknownSymbol, MacintoshKorean][Attributes]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][Attributes]
 *                   Missing[UnknownSymbol, MacintoshRomanian][Attributes]
 *                   Missing[UnknownSymbol, MacintoshRoman][Attributes]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][Attributes]
 *                   Missing[UnknownSymbol, MacintoshThai][Attributes]
 *                   Missing[UnknownSymbol, MacintoshTurkish][Attributes]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][Attributes]
 *                   Missing[UnknownSymbol, Math1][Attributes]
 *                   Missing[UnknownSymbol, Math2][Attributes]
 *                   Missing[UnknownSymbol, Math3][Attributes]
 *                   Missing[UnknownSymbol, Math4][Attributes]
 *                   Missing[UnknownSymbol, Math5][Attributes]
 *                   Missing[UnknownSymbol, Mathematica1][Attributes]
 *                   Missing[UnknownSymbol, Mathematica2][Attributes]
 *                   Missing[UnknownSymbol, Mathematica3][Attributes]
 *                   Missing[UnknownSymbol, Mathematica4][Attributes]
 *                   Missing[UnknownSymbol, Mathematica5][Attributes]
 *                   Missing[UnknownSymbol, Mathematica6][Attributes]
 *                   Missing[UnknownSymbol, Mathematica7][Attributes]
 *                   Missing[UnknownSymbol, PrintableASCII][Attributes]
 *                   Missing[UnknownSymbol, ShiftJIS][Attributes]
 *                   Locked Protected
 *                   Missing[UnknownSymbol, UTF-8][Attributes]
 *                   Missing[UnknownSymbol, UTF8][Attributes]
 *                   Missing[UnknownSymbol, WindowsANSI][Attributes]
 *                   Missing[UnknownSymbol, WindowsBaltic][Attributes]
 *                   Missing[UnknownSymbol, WindowsCyrillic][Attributes]
 *                   Missing[UnknownSymbol, WindowsEastEurope][Attributes]
 *                   Missing[UnknownSymbol, WindowsGreek][Attributes]
 *                   Missing[UnknownSymbol, WindowsThai][Attributes]
 *                   Missing[UnknownSymbol, WindowsTurkish][Attributes]
 * Attributes:       Missing[UnknownSymbol, ZapfDingbats][Attributes]
 *
 *                   local: <>{Missing[UnknownSymbol, AdobeStandard][Documentation], Missing[UnknownSymbol, ASCII][Documentation], Missing[UnknownSymbol, CP936][Documentation], Missing[UnknownSymbol, CP949][Documentation], Missing[UnknownSymbol, CP950][Documentation], Missing[UnknownSymbol, Custom][Documentation], Missing[UnknownSymbol, EUC-JP][Documentation], Missing[UnknownSymbol, EUC][Documentation], Missing[UnknownSymbol, IBM-850][Documentation], Missing[UnknownSymbol, ISO8859-10][Documentation], Missing[UnknownSymbol, ISO8859-11][Documentation], Missing[UnknownSymbol, ISO8859-13][Documentation], Missing[UnknownSymbol, ISO8859-14][Documentation], Missing[UnknownSymbol, ISO8859-15][Documentation], Missing[UnknownSymbol, ISO8859-16][Documentation], Missing[UnknownSymbol, ISO8859-1][Documentation], Missing[UnknownSymbol, ISO8859-2][Documentation], Missing[UnknownSymbol, ISO8859-3][Documentation], Missing[UnknownSymbol, ISO8859-4][Documentation], Missing[UnknownSymbol, ISO8859-5][Documentation], Missing[UnknownSymbol, ISO8859-6][Documentation], Missing[UnknownSymbol, ISO8859-7][Documentation], Missing[UnknownSymbol, ISO8859-8][Documentation], Missing[UnknownSymbol, ISO8859-9][Documentation], Missing[UnknownSymbol, ISOLatin1][Documentation], Missing[UnknownSymbol, ISOLatin2][Documentation], Missing[UnknownSymbol, ISOLatin3][Documentation], Missing[UnknownSymbol, ISOLatin4][Documentation], Missing[UnknownSymbol, ISOLatinCyrillic][Documentation], Missing[UnknownSymbol, Klingon][Documentation], Missing[UnknownSymbol, koi8-r][Documentation], Missing[UnknownSymbol, MacintoshArabic][Documentation], Missing[UnknownSymbol, MacintoshChineseSimplified][Documentation], Missing[UnknownSymbol, MacintoshChineseTraditional][Documentation], Missing[UnknownSymbol, MacintoshCroatian][Documentation], Missing[UnknownSymbol, MacintoshCyrillic][Documentation], Missing[UnknownSymbol, MacintoshGreek][Documentation], Missing[UnknownSymbol, MacintoshHebrew][Documentation], Missing[UnknownSymbol, MacintoshIcelandic][Documentation], Missing[UnknownSymbol, MacintoshKorean][Documentation], Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][Documentation], Missing[UnknownSymbol, MacintoshRomanian][Documentation], Missing[UnknownSymbol, MacintoshRoman][Documentation], Missing[UnknownSymbol, MacintoshRomanPDFExport][Documentation], Missing[UnknownSymbol, MacintoshThai][Documentation], Missing[UnknownSymbol, MacintoshTurkish][Documentation], Missing[UnknownSymbol, MacintoshUkrainian][Documentation], Missing[UnknownSymbol, Math1][Documentation], Missing[UnknownSymbol, Math2][Documentation], Missing[UnknownSymbol, Math3][Documentation], Missing[UnknownSymbol, Math4][Documentation], Missing[UnknownSymbol, Math5][Documentation], Missing[UnknownSymbol, Mathematica1][Documentation], Missing[UnknownSymbol, Mathematica2][Documentation], Missing[UnknownSymbol, Mathematica3][Documentation], Missing[UnknownSymbol, Mathematica4][Documentation], Missing[UnknownSymbol, Mathematica5][Documentation], Missing[UnknownSymbol, Mathematica6][Documentation], Missing[UnknownSymbol, Mathematica7][Documentation], Missing[UnknownSymbol, PrintableASCII][Documentation], Missing[UnknownSymbol, ShiftJIS][Documentation], <|Local -> paclet:ref/Symbol, Web -> http://reference.wolfram.com/language/ref/Symbol.html|>, Missing[UnknownSymbol, UTF-8][Documentation], Missing[UnknownSymbol, UTF8][Documentation], Missing[UnknownSymbol, WindowsANSI][Documentation], Missing[UnknownSymbol, WindowsBaltic][Documentation], Missing[UnknownSymbol, WindowsCyrillic][Documentation], Missing[UnknownSymbol, WindowsEastEurope][Documentation], Missing[UnknownSymbol, WindowsGreek][Documentation], Missing[UnknownSymbol, WindowsThai][Documentation], Missing[UnknownSymbol, WindowsTurkish][Documentation], Missing[UnknownSymbol, ZapfDingbats][Documentation]}[Local]
 * Documentation:    web: <>{Missing[UnknownSymbol, AdobeStandard][Documentation], Missing[UnknownSymbol, ASCII][Documentation], Missing[UnknownSymbol, CP936][Documentation], Missing[UnknownSymbol, CP949][Documentation], Missing[UnknownSymbol, CP950][Documentation], Missing[UnknownSymbol, Custom][Documentation], Missing[UnknownSymbol, EUC-JP][Documentation], Missing[UnknownSymbol, EUC][Documentation], Missing[UnknownSymbol, IBM-850][Documentation], Missing[UnknownSymbol, ISO8859-10][Documentation], Missing[UnknownSymbol, ISO8859-11][Documentation], Missing[UnknownSymbol, ISO8859-13][Documentation], Missing[UnknownSymbol, ISO8859-14][Documentation], Missing[UnknownSymbol, ISO8859-15][Documentation], Missing[UnknownSymbol, ISO8859-16][Documentation], Missing[UnknownSymbol, ISO8859-1][Documentation], Missing[UnknownSymbol, ISO8859-2][Documentation], Missing[UnknownSymbol, ISO8859-3][Documentation], Missing[UnknownSymbol, ISO8859-4][Documentation], Missing[UnknownSymbol, ISO8859-5][Documentation], Missing[UnknownSymbol, ISO8859-6][Documentation], Missing[UnknownSymbol, ISO8859-7][Documentation], Missing[UnknownSymbol, ISO8859-8][Documentation], Missing[UnknownSymbol, ISO8859-9][Documentation], Missing[UnknownSymbol, ISOLatin1][Documentation], Missing[UnknownSymbol, ISOLatin2][Documentation], Missing[UnknownSymbol, ISOLatin3][Documentation], Missing[UnknownSymbol, ISOLatin4][Documentation], Missing[UnknownSymbol, ISOLatinCyrillic][Documentation], Missing[UnknownSymbol, Klingon][Documentation], Missing[UnknownSymbol, koi8-r][Documentation], Missing[UnknownSymbol, MacintoshArabic][Documentation], Missing[UnknownSymbol, MacintoshChineseSimplified][Documentation], Missing[UnknownSymbol, MacintoshChineseTraditional][Documentation], Missing[UnknownSymbol, MacintoshCroatian][Documentation], Missing[UnknownSymbol, MacintoshCyrillic][Documentation], Missing[UnknownSymbol, MacintoshGreek][Documentation], Missing[UnknownSymbol, MacintoshHebrew][Documentation], Missing[UnknownSymbol, MacintoshIcelandic][Documentation], Missing[UnknownSymbol, MacintoshKorean][Documentation], Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][Documentation], Missing[UnknownSymbol, MacintoshRomanian][Documentation], Missing[UnknownSymbol, MacintoshRoman][Documentation], Missing[UnknownSymbol, MacintoshRomanPDFExport][Documentation], Missing[UnknownSymbol, MacintoshThai][Documentation], Missing[UnknownSymbol, MacintoshTurkish][Documentation], Missing[UnknownSymbol, MacintoshUkrainian][Documentation], Missing[UnknownSymbol, Math1][Documentation], Missing[UnknownSymbol, Math2][Documentation], Missing[UnknownSymbol, Math3][Documentation], Missing[UnknownSymbol, Math4][Documentation], Missing[UnknownSymbol, Math5][Documentation], Missing[UnknownSymbol, Mathematica1][Documentation], Missing[UnknownSymbol, Mathematica2][Documentation], Missing[UnknownSymbol, Mathematica3][Documentation], Missing[UnknownSymbol, Mathematica4][Documentation], Missing[UnknownSymbol, Mathematica5][Documentation], Missing[UnknownSymbol, Mathematica6][Documentation], Missing[UnknownSymbol, Mathematica7][Documentation], Missing[UnknownSymbol, PrintableASCII][Documentation], Missing[UnknownSymbol, ShiftJIS][Documentation], <|Local -> paclet:ref/Symbol, Web -> http://reference.wolfram.com/language/ref/Symbol.html|>, Missing[UnknownSymbol, UTF-8][Documentation], Missing[UnknownSymbol, UTF8][Documentation], Missing[UnknownSymbol, WindowsANSI][Documentation], Missing[UnknownSymbol, WindowsBaltic][Documentation], Missing[UnknownSymbol, WindowsCyrillic][Documentation], Missing[UnknownSymbol, WindowsEastEurope][Documentation], Missing[UnknownSymbol, WindowsGreek][Documentation], Missing[UnknownSymbol, WindowsThai][Documentation], Missing[UnknownSymbol, WindowsTurkish][Documentation], Missing[UnknownSymbol, ZapfDingbats][Documentation]}[Web]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][Definitions]
 *                   Missing[UnknownSymbol, ASCII][Definitions]
 *                   Missing[UnknownSymbol, CP936][Definitions]
 *                   Missing[UnknownSymbol, CP949][Definitions]
 *                   Missing[UnknownSymbol, CP950][Definitions]
 *                   Missing[UnknownSymbol, Custom][Definitions]
 *                   Missing[UnknownSymbol, EUC-JP][Definitions]
 *                   Missing[UnknownSymbol, EUC][Definitions]
 *                   Missing[UnknownSymbol, IBM-850][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-10][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-11][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-13][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-14][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-15][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-16][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-1][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-2][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-3][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-4][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-5][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-6][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-7][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-8][Definitions]
 *                   Missing[UnknownSymbol, ISO8859-9][Definitions]
 *                   Missing[UnknownSymbol, ISOLatin1][Definitions]
 *                   Missing[UnknownSymbol, ISOLatin2][Definitions]
 *                   Missing[UnknownSymbol, ISOLatin3][Definitions]
 *                   Missing[UnknownSymbol, ISOLatin4][Definitions]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][Definitions]
 *                   Missing[UnknownSymbol, Klingon][Definitions]
 *                   Missing[UnknownSymbol, koi8-r][Definitions]
 *                   Missing[UnknownSymbol, MacintoshArabic][Definitions]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][Definitions]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][Definitions]
 *                   Missing[UnknownSymbol, MacintoshCroatian][Definitions]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][Definitions]
 *                   Missing[UnknownSymbol, MacintoshGreek][Definitions]
 *                   Missing[UnknownSymbol, MacintoshHebrew][Definitions]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][Definitions]
 *                   Missing[UnknownSymbol, MacintoshKorean][Definitions]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][Definitions]
 *                   Missing[UnknownSymbol, MacintoshRomanian][Definitions]
 *                   Missing[UnknownSymbol, MacintoshRoman][Definitions]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][Definitions]
 *                   Missing[UnknownSymbol, MacintoshThai][Definitions]
 *                   Missing[UnknownSymbol, MacintoshTurkish][Definitions]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][Definitions]
 *                   Missing[UnknownSymbol, Math1][Definitions]
 *                   Missing[UnknownSymbol, Math2][Definitions]
 *                   Missing[UnknownSymbol, Math3][Definitions]
 *                   Missing[UnknownSymbol, Math4][Definitions]
 *                   Missing[UnknownSymbol, Math5][Definitions]
 *                   Missing[UnknownSymbol, Mathematica1][Definitions]
 *                   Missing[UnknownSymbol, Mathematica2][Definitions]
 *                   Missing[UnknownSymbol, Mathematica3][Definitions]
 *                   Missing[UnknownSymbol, Mathematica4][Definitions]
 *                   Missing[UnknownSymbol, Mathematica5][Definitions]
 *                   Missing[UnknownSymbol, Mathematica6][Definitions]
 *                   Missing[UnknownSymbol, Mathematica7][Definitions]
 *                   Missing[UnknownSymbol, PrintableASCII][Definitions]
 *                   Missing[UnknownSymbol, ShiftJIS][Definitions]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][Definitions]
 *                   Missing[UnknownSymbol, UTF8][Definitions]
 *                   Missing[UnknownSymbol, WindowsANSI][Definitions]
 *                   Missing[UnknownSymbol, WindowsBaltic][Definitions]
 *                   Missing[UnknownSymbol, WindowsCyrillic][Definitions]
 *                   Missing[UnknownSymbol, WindowsEastEurope][Definitions]
 *                   Missing[UnknownSymbol, WindowsGreek][Definitions]
 *                   Missing[UnknownSymbol, WindowsThai][Definitions]
 *                   Missing[UnknownSymbol, WindowsTurkish][Definitions]
 * Definitions:      Missing[UnknownSymbol, ZapfDingbats][Definitions]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][OwnValues]
 *                   Missing[UnknownSymbol, ASCII][OwnValues]
 *                   Missing[UnknownSymbol, CP936][OwnValues]
 *                   Missing[UnknownSymbol, CP949][OwnValues]
 *                   Missing[UnknownSymbol, CP950][OwnValues]
 *                   Missing[UnknownSymbol, Custom][OwnValues]
 *                   Missing[UnknownSymbol, EUC-JP][OwnValues]
 *                   Missing[UnknownSymbol, EUC][OwnValues]
 *                   Missing[UnknownSymbol, IBM-850][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-10][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-11][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-13][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-14][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-15][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-16][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-1][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-2][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-3][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-4][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-5][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-6][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-7][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-8][OwnValues]
 *                   Missing[UnknownSymbol, ISO8859-9][OwnValues]
 *                   Missing[UnknownSymbol, ISOLatin1][OwnValues]
 *                   Missing[UnknownSymbol, ISOLatin2][OwnValues]
 *                   Missing[UnknownSymbol, ISOLatin3][OwnValues]
 *                   Missing[UnknownSymbol, ISOLatin4][OwnValues]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][OwnValues]
 *                   Missing[UnknownSymbol, Klingon][OwnValues]
 *                   Missing[UnknownSymbol, koi8-r][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshArabic][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshCroatian][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshGreek][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshHebrew][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshKorean][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshRomanian][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshRoman][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshThai][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshTurkish][OwnValues]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][OwnValues]
 *                   Missing[UnknownSymbol, Math1][OwnValues]
 *                   Missing[UnknownSymbol, Math2][OwnValues]
 *                   Missing[UnknownSymbol, Math3][OwnValues]
 *                   Missing[UnknownSymbol, Math4][OwnValues]
 *                   Missing[UnknownSymbol, Math5][OwnValues]
 *                   Missing[UnknownSymbol, Mathematica1][OwnValues]
 *                   Missing[UnknownSymbol, Mathematica2][OwnValues]
 *                   Missing[UnknownSymbol, Mathematica3][OwnValues]
 *                   Missing[UnknownSymbol, Mathematica4][OwnValues]
 *                   Missing[UnknownSymbol, Mathematica5][OwnValues]
 *                   Missing[UnknownSymbol, Mathematica6][OwnValues]
 *                   Missing[UnknownSymbol, Mathematica7][OwnValues]
 *                   Missing[UnknownSymbol, PrintableASCII][OwnValues]
 *                   Missing[UnknownSymbol, ShiftJIS][OwnValues]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][OwnValues]
 *                   Missing[UnknownSymbol, UTF8][OwnValues]
 *                   Missing[UnknownSymbol, WindowsANSI][OwnValues]
 *                   Missing[UnknownSymbol, WindowsBaltic][OwnValues]
 *                   Missing[UnknownSymbol, WindowsCyrillic][OwnValues]
 *                   Missing[UnknownSymbol, WindowsEastEurope][OwnValues]
 *                   Missing[UnknownSymbol, WindowsGreek][OwnValues]
 *                   Missing[UnknownSymbol, WindowsThai][OwnValues]
 *                   Missing[UnknownSymbol, WindowsTurkish][OwnValues]
 * Own values:       Missing[UnknownSymbol, ZapfDingbats][OwnValues]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][DownValues]
 *                   Missing[UnknownSymbol, ASCII][DownValues]
 *                   Missing[UnknownSymbol, CP936][DownValues]
 *                   Missing[UnknownSymbol, CP949][DownValues]
 *                   Missing[UnknownSymbol, CP950][DownValues]
 *                   Missing[UnknownSymbol, Custom][DownValues]
 *                   Missing[UnknownSymbol, EUC-JP][DownValues]
 *                   Missing[UnknownSymbol, EUC][DownValues]
 *                   Missing[UnknownSymbol, IBM-850][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-10][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-11][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-13][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-14][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-15][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-16][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-1][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-2][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-3][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-4][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-5][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-6][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-7][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-8][DownValues]
 *                   Missing[UnknownSymbol, ISO8859-9][DownValues]
 *                   Missing[UnknownSymbol, ISOLatin1][DownValues]
 *                   Missing[UnknownSymbol, ISOLatin2][DownValues]
 *                   Missing[UnknownSymbol, ISOLatin3][DownValues]
 *                   Missing[UnknownSymbol, ISOLatin4][DownValues]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][DownValues]
 *                   Missing[UnknownSymbol, Klingon][DownValues]
 *                   Missing[UnknownSymbol, koi8-r][DownValues]
 *                   Missing[UnknownSymbol, MacintoshArabic][DownValues]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][DownValues]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][DownValues]
 *                   Missing[UnknownSymbol, MacintoshCroatian][DownValues]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][DownValues]
 *                   Missing[UnknownSymbol, MacintoshGreek][DownValues]
 *                   Missing[UnknownSymbol, MacintoshHebrew][DownValues]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][DownValues]
 *                   Missing[UnknownSymbol, MacintoshKorean][DownValues]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][DownValues]
 *                   Missing[UnknownSymbol, MacintoshRomanian][DownValues]
 *                   Missing[UnknownSymbol, MacintoshRoman][DownValues]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][DownValues]
 *                   Missing[UnknownSymbol, MacintoshThai][DownValues]
 *                   Missing[UnknownSymbol, MacintoshTurkish][DownValues]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][DownValues]
 *                   Missing[UnknownSymbol, Math1][DownValues]
 *                   Missing[UnknownSymbol, Math2][DownValues]
 *                   Missing[UnknownSymbol, Math3][DownValues]
 *                   Missing[UnknownSymbol, Math4][DownValues]
 *                   Missing[UnknownSymbol, Math5][DownValues]
 *                   Missing[UnknownSymbol, Mathematica1][DownValues]
 *                   Missing[UnknownSymbol, Mathematica2][DownValues]
 *                   Missing[UnknownSymbol, Mathematica3][DownValues]
 *                   Missing[UnknownSymbol, Mathematica4][DownValues]
 *                   Missing[UnknownSymbol, Mathematica5][DownValues]
 *                   Missing[UnknownSymbol, Mathematica6][DownValues]
 *                   Missing[UnknownSymbol, Mathematica7][DownValues]
 *                   Missing[UnknownSymbol, PrintableASCII][DownValues]
 *                   Missing[UnknownSymbol, ShiftJIS][DownValues]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][DownValues]
 *                   Missing[UnknownSymbol, UTF8][DownValues]
 *                   Missing[UnknownSymbol, WindowsANSI][DownValues]
 *                   Missing[UnknownSymbol, WindowsBaltic][DownValues]
 *                   Missing[UnknownSymbol, WindowsCyrillic][DownValues]
 *                   Missing[UnknownSymbol, WindowsEastEurope][DownValues]
 *                   Missing[UnknownSymbol, WindowsGreek][DownValues]
 *                   Missing[UnknownSymbol, WindowsThai][DownValues]
 *                   Missing[UnknownSymbol, WindowsTurkish][DownValues]
 * Down values:      Missing[UnknownSymbol, ZapfDingbats][DownValues]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][UpValues]
 *                   Missing[UnknownSymbol, ASCII][UpValues]
 *                   Missing[UnknownSymbol, CP936][UpValues]
 *                   Missing[UnknownSymbol, CP949][UpValues]
 *                   Missing[UnknownSymbol, CP950][UpValues]
 *                   Missing[UnknownSymbol, Custom][UpValues]
 *                   Missing[UnknownSymbol, EUC-JP][UpValues]
 *                   Missing[UnknownSymbol, EUC][UpValues]
 *                   Missing[UnknownSymbol, IBM-850][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-10][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-11][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-13][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-14][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-15][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-16][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-1][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-2][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-3][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-4][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-5][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-6][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-7][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-8][UpValues]
 *                   Missing[UnknownSymbol, ISO8859-9][UpValues]
 *                   Missing[UnknownSymbol, ISOLatin1][UpValues]
 *                   Missing[UnknownSymbol, ISOLatin2][UpValues]
 *                   Missing[UnknownSymbol, ISOLatin3][UpValues]
 *                   Missing[UnknownSymbol, ISOLatin4][UpValues]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][UpValues]
 *                   Missing[UnknownSymbol, Klingon][UpValues]
 *                   Missing[UnknownSymbol, koi8-r][UpValues]
 *                   Missing[UnknownSymbol, MacintoshArabic][UpValues]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][UpValues]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][UpValues]
 *                   Missing[UnknownSymbol, MacintoshCroatian][UpValues]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][UpValues]
 *                   Missing[UnknownSymbol, MacintoshGreek][UpValues]
 *                   Missing[UnknownSymbol, MacintoshHebrew][UpValues]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][UpValues]
 *                   Missing[UnknownSymbol, MacintoshKorean][UpValues]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][UpValues]
 *                   Missing[UnknownSymbol, MacintoshRomanian][UpValues]
 *                   Missing[UnknownSymbol, MacintoshRoman][UpValues]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][UpValues]
 *                   Missing[UnknownSymbol, MacintoshThai][UpValues]
 *                   Missing[UnknownSymbol, MacintoshTurkish][UpValues]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][UpValues]
 *                   Missing[UnknownSymbol, Math1][UpValues]
 *                   Missing[UnknownSymbol, Math2][UpValues]
 *                   Missing[UnknownSymbol, Math3][UpValues]
 *                   Missing[UnknownSymbol, Math4][UpValues]
 *                   Missing[UnknownSymbol, Math5][UpValues]
 *                   Missing[UnknownSymbol, Mathematica1][UpValues]
 *                   Missing[UnknownSymbol, Mathematica2][UpValues]
 *                   Missing[UnknownSymbol, Mathematica3][UpValues]
 *                   Missing[UnknownSymbol, Mathematica4][UpValues]
 *                   Missing[UnknownSymbol, Mathematica5][UpValues]
 *                   Missing[UnknownSymbol, Mathematica6][UpValues]
 *                   Missing[UnknownSymbol, Mathematica7][UpValues]
 *                   Missing[UnknownSymbol, PrintableASCII][UpValues]
 *                   Missing[UnknownSymbol, ShiftJIS][UpValues]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][UpValues]
 *                   Missing[UnknownSymbol, UTF8][UpValues]
 *                   Missing[UnknownSymbol, WindowsANSI][UpValues]
 *                   Missing[UnknownSymbol, WindowsBaltic][UpValues]
 *                   Missing[UnknownSymbol, WindowsCyrillic][UpValues]
 *                   Missing[UnknownSymbol, WindowsEastEurope][UpValues]
 *                   Missing[UnknownSymbol, WindowsGreek][UpValues]
 *                   Missing[UnknownSymbol, WindowsThai][UpValues]
 *                   Missing[UnknownSymbol, WindowsTurkish][UpValues]
 * Up values:        Missing[UnknownSymbol, ZapfDingbats][UpValues]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][SubValues]
 *                   Missing[UnknownSymbol, ASCII][SubValues]
 *                   Missing[UnknownSymbol, CP936][SubValues]
 *                   Missing[UnknownSymbol, CP949][SubValues]
 *                   Missing[UnknownSymbol, CP950][SubValues]
 *                   Missing[UnknownSymbol, Custom][SubValues]
 *                   Missing[UnknownSymbol, EUC-JP][SubValues]
 *                   Missing[UnknownSymbol, EUC][SubValues]
 *                   Missing[UnknownSymbol, IBM-850][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-10][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-11][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-13][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-14][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-15][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-16][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-1][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-2][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-3][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-4][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-5][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-6][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-7][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-8][SubValues]
 *                   Missing[UnknownSymbol, ISO8859-9][SubValues]
 *                   Missing[UnknownSymbol, ISOLatin1][SubValues]
 *                   Missing[UnknownSymbol, ISOLatin2][SubValues]
 *                   Missing[UnknownSymbol, ISOLatin3][SubValues]
 *                   Missing[UnknownSymbol, ISOLatin4][SubValues]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][SubValues]
 *                   Missing[UnknownSymbol, Klingon][SubValues]
 *                   Missing[UnknownSymbol, koi8-r][SubValues]
 *                   Missing[UnknownSymbol, MacintoshArabic][SubValues]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][SubValues]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][SubValues]
 *                   Missing[UnknownSymbol, MacintoshCroatian][SubValues]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][SubValues]
 *                   Missing[UnknownSymbol, MacintoshGreek][SubValues]
 *                   Missing[UnknownSymbol, MacintoshHebrew][SubValues]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][SubValues]
 *                   Missing[UnknownSymbol, MacintoshKorean][SubValues]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][SubValues]
 *                   Missing[UnknownSymbol, MacintoshRomanian][SubValues]
 *                   Missing[UnknownSymbol, MacintoshRoman][SubValues]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][SubValues]
 *                   Missing[UnknownSymbol, MacintoshThai][SubValues]
 *                   Missing[UnknownSymbol, MacintoshTurkish][SubValues]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][SubValues]
 *                   Missing[UnknownSymbol, Math1][SubValues]
 *                   Missing[UnknownSymbol, Math2][SubValues]
 *                   Missing[UnknownSymbol, Math3][SubValues]
 *                   Missing[UnknownSymbol, Math4][SubValues]
 *                   Missing[UnknownSymbol, Math5][SubValues]
 *                   Missing[UnknownSymbol, Mathematica1][SubValues]
 *                   Missing[UnknownSymbol, Mathematica2][SubValues]
 *                   Missing[UnknownSymbol, Mathematica3][SubValues]
 *                   Missing[UnknownSymbol, Mathematica4][SubValues]
 *                   Missing[UnknownSymbol, Mathematica5][SubValues]
 *                   Missing[UnknownSymbol, Mathematica6][SubValues]
 *                   Missing[UnknownSymbol, Mathematica7][SubValues]
 *                   Missing[UnknownSymbol, PrintableASCII][SubValues]
 *                   Missing[UnknownSymbol, ShiftJIS][SubValues]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][SubValues]
 *                   Missing[UnknownSymbol, UTF8][SubValues]
 *                   Missing[UnknownSymbol, WindowsANSI][SubValues]
 *                   Missing[UnknownSymbol, WindowsBaltic][SubValues]
 *                   Missing[UnknownSymbol, WindowsCyrillic][SubValues]
 *                   Missing[UnknownSymbol, WindowsEastEurope][SubValues]
 *                   Missing[UnknownSymbol, WindowsGreek][SubValues]
 *                   Missing[UnknownSymbol, WindowsThai][SubValues]
 *                   Missing[UnknownSymbol, WindowsTurkish][SubValues]
 * Sub values:       Missing[UnknownSymbol, ZapfDingbats][SubValues]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][DefaultValues]
 *                   Missing[UnknownSymbol, ASCII][DefaultValues]
 *                   Missing[UnknownSymbol, CP936][DefaultValues]
 *                   Missing[UnknownSymbol, CP949][DefaultValues]
 *                   Missing[UnknownSymbol, CP950][DefaultValues]
 *                   Missing[UnknownSymbol, Custom][DefaultValues]
 *                   Missing[UnknownSymbol, EUC-JP][DefaultValues]
 *                   Missing[UnknownSymbol, EUC][DefaultValues]
 *                   Missing[UnknownSymbol, IBM-850][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-10][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-11][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-13][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-14][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-15][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-16][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-1][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-2][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-3][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-4][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-5][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-6][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-7][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-8][DefaultValues]
 *                   Missing[UnknownSymbol, ISO8859-9][DefaultValues]
 *                   Missing[UnknownSymbol, ISOLatin1][DefaultValues]
 *                   Missing[UnknownSymbol, ISOLatin2][DefaultValues]
 *                   Missing[UnknownSymbol, ISOLatin3][DefaultValues]
 *                   Missing[UnknownSymbol, ISOLatin4][DefaultValues]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][DefaultValues]
 *                   Missing[UnknownSymbol, Klingon][DefaultValues]
 *                   Missing[UnknownSymbol, koi8-r][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshArabic][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshCroatian][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshGreek][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshHebrew][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshKorean][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshRomanian][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshRoman][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshThai][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshTurkish][DefaultValues]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][DefaultValues]
 *                   Missing[UnknownSymbol, Math1][DefaultValues]
 *                   Missing[UnknownSymbol, Math2][DefaultValues]
 *                   Missing[UnknownSymbol, Math3][DefaultValues]
 *                   Missing[UnknownSymbol, Math4][DefaultValues]
 *                   Missing[UnknownSymbol, Math5][DefaultValues]
 *                   Missing[UnknownSymbol, Mathematica1][DefaultValues]
 *                   Missing[UnknownSymbol, Mathematica2][DefaultValues]
 *                   Missing[UnknownSymbol, Mathematica3][DefaultValues]
 *                   Missing[UnknownSymbol, Mathematica4][DefaultValues]
 *                   Missing[UnknownSymbol, Mathematica5][DefaultValues]
 *                   Missing[UnknownSymbol, Mathematica6][DefaultValues]
 *                   Missing[UnknownSymbol, Mathematica7][DefaultValues]
 *                   Missing[UnknownSymbol, PrintableASCII][DefaultValues]
 *                   Missing[UnknownSymbol, ShiftJIS][DefaultValues]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][DefaultValues]
 *                   Missing[UnknownSymbol, UTF8][DefaultValues]
 *                   Missing[UnknownSymbol, WindowsANSI][DefaultValues]
 *                   Missing[UnknownSymbol, WindowsBaltic][DefaultValues]
 *                   Missing[UnknownSymbol, WindowsCyrillic][DefaultValues]
 *                   Missing[UnknownSymbol, WindowsEastEurope][DefaultValues]
 *                   Missing[UnknownSymbol, WindowsGreek][DefaultValues]
 *                   Missing[UnknownSymbol, WindowsThai][DefaultValues]
 *                   Missing[UnknownSymbol, WindowsTurkish][DefaultValues]
 * Default value:    Missing[UnknownSymbol, ZapfDingbats][DefaultValues]
 *
 *                   Missing[UnknownSymbol, AdobeStandard][NValues]
 *                   Missing[UnknownSymbol, ASCII][NValues]
 *                   Missing[UnknownSymbol, CP936][NValues]
 *                   Missing[UnknownSymbol, CP949][NValues]
 *                   Missing[UnknownSymbol, CP950][NValues]
 *                   Missing[UnknownSymbol, Custom][NValues]
 *                   Missing[UnknownSymbol, EUC-JP][NValues]
 *                   Missing[UnknownSymbol, EUC][NValues]
 *                   Missing[UnknownSymbol, IBM-850][NValues]
 *                   Missing[UnknownSymbol, ISO8859-10][NValues]
 *                   Missing[UnknownSymbol, ISO8859-11][NValues]
 *                   Missing[UnknownSymbol, ISO8859-13][NValues]
 *                   Missing[UnknownSymbol, ISO8859-14][NValues]
 *                   Missing[UnknownSymbol, ISO8859-15][NValues]
 *                   Missing[UnknownSymbol, ISO8859-16][NValues]
 *                   Missing[UnknownSymbol, ISO8859-1][NValues]
 *                   Missing[UnknownSymbol, ISO8859-2][NValues]
 *                   Missing[UnknownSymbol, ISO8859-3][NValues]
 *                   Missing[UnknownSymbol, ISO8859-4][NValues]
 *                   Missing[UnknownSymbol, ISO8859-5][NValues]
 *                   Missing[UnknownSymbol, ISO8859-6][NValues]
 *                   Missing[UnknownSymbol, ISO8859-7][NValues]
 *                   Missing[UnknownSymbol, ISO8859-8][NValues]
 *                   Missing[UnknownSymbol, ISO8859-9][NValues]
 *                   Missing[UnknownSymbol, ISOLatin1][NValues]
 *                   Missing[UnknownSymbol, ISOLatin2][NValues]
 *                   Missing[UnknownSymbol, ISOLatin3][NValues]
 *                   Missing[UnknownSymbol, ISOLatin4][NValues]
 *                   Missing[UnknownSymbol, ISOLatinCyrillic][NValues]
 *                   Missing[UnknownSymbol, Klingon][NValues]
 *                   Missing[UnknownSymbol, koi8-r][NValues]
 *                   Missing[UnknownSymbol, MacintoshArabic][NValues]
 *                   Missing[UnknownSymbol, MacintoshChineseSimplified][NValues]
 *                   Missing[UnknownSymbol, MacintoshChineseTraditional][NValues]
 *                   Missing[UnknownSymbol, MacintoshCroatian][NValues]
 *                   Missing[UnknownSymbol, MacintoshCyrillic][NValues]
 *                   Missing[UnknownSymbol, MacintoshGreek][NValues]
 *                   Missing[UnknownSymbol, MacintoshHebrew][NValues]
 *                   Missing[UnknownSymbol, MacintoshIcelandic][NValues]
 *                   Missing[UnknownSymbol, MacintoshKorean][NValues]
 *                   Missing[UnknownSymbol, MacintoshNonCyrillicSlavic][NValues]
 *                   Missing[UnknownSymbol, MacintoshRomanian][NValues]
 *                   Missing[UnknownSymbol, MacintoshRoman][NValues]
 *                   Missing[UnknownSymbol, MacintoshRomanPDFExport][NValues]
 *                   Missing[UnknownSymbol, MacintoshThai][NValues]
 *                   Missing[UnknownSymbol, MacintoshTurkish][NValues]
 *                   Missing[UnknownSymbol, MacintoshUkrainian][NValues]
 *                   Missing[UnknownSymbol, Math1][NValues]
 *                   Missing[UnknownSymbol, Math2][NValues]
 *                   Missing[UnknownSymbol, Math3][NValues]
 *                   Missing[UnknownSymbol, Math4][NValues]
 *                   Missing[UnknownSymbol, Math5][NValues]
 *                   Missing[UnknownSymbol, Mathematica1][NValues]
 *                   Missing[UnknownSymbol, Mathematica2][NValues]
 *                   Missing[UnknownSymbol, Mathematica3][NValues]
 *                   Missing[UnknownSymbol, Mathematica4][NValues]
 *                   Missing[UnknownSymbol, Mathematica5][NValues]
 *                   Missing[UnknownSymbol, Mathematica6][NValues]
 *                   Missing[UnknownSymbol, Mathematica7][NValues]
 *                   Missing[UnknownSymbol, PrintableASCII][NValues]
 *                   Missing[UnknownSymbol, ShiftJIS][NValues]
 *                   None
 *                   Missing[UnknownSymbol, UTF-8][NValues]
 *                   Missing[UnknownSymbol, UTF8][NValues]
 *                   Missing[UnknownSymbol, WindowsANSI][NValues]
 *                   Missing[UnknownSymbol, WindowsBaltic][NValues]
 *                   Missing[UnknownSymbol, WindowsCyrillic][NValues]
 *                   Missing[UnknownSymbol, WindowsEastEurope][NValues]
 *                   Missing[UnknownSymbol, WindowsGreek][NValues]
 *                   Missing[UnknownSymbol, WindowsThai][NValues]
 *                   Missing[UnknownSymbol, WindowsTurkish][NValues]
 * Numeric values:   Missing[UnknownSymbol, ZapfDingbats][NValues]
 */
fun `$CharacterEncodings`(vararg arguments: Any?, options: MutableMap<String, Any?> = mutableMapOf()): MathematicaFunction {
	return MathematicaFunction("\$CharacterEncodings", arguments.toMutableList(), options)
}
