package com.daniloaraujosilva.mathemagika.library.jvm.functions

import com.daniloaraujosilva.mathemagika.library.jvm.common.MathematicaFunction

/**
 *````
 *
 *                   BingMaps
 *                   DeviantArt
 *                   EsriMap
 *                   GoogleDocs
 *                   GoogleForms
 *                   GoogleMaps
 *                   GoogleSheets
 *                   GoogleSlides
 *                   Imgur
 *                   Instagram
 *                   OpenStreetMap
 *                   Reddit
 *                   SoundCloud
 *                   Twitter
 *                   UStream
 *                   Vimeo
 *                   Vine
 * Name:             YouTube
 *
 *                   Missing[UnknownSymbol, BingMaps][FullName]
 *                   Missing[UnknownSymbol, DeviantArt][FullName]
 *                   Missing[UnknownSymbol, EsriMap][FullName]
 *                   Missing[UnknownSymbol, GoogleDocs][FullName]
 *                   Missing[UnknownSymbol, GoogleForms][FullName]
 *                   Missing[UnknownSymbol, GoogleMaps][FullName]
 *                   Missing[UnknownSymbol, GoogleSheets][FullName]
 *                   Missing[UnknownSymbol, GoogleSlides][FullName]
 *                   Missing[UnknownSymbol, Imgur][FullName]
 *                   Missing[UnknownSymbol, Instagram][FullName]
 *                   Missing[UnknownSymbol, OpenStreetMap][FullName]
 *                   Missing[UnknownSymbol, Reddit][FullName]
 *                   Missing[UnknownSymbol, SoundCloud][FullName]
 *                   Missing[UnknownSymbol, Twitter][FullName]
 *                   Missing[UnknownSymbol, UStream][FullName]
 *                   Missing[UnknownSymbol, Vimeo][FullName]
 *                   Missing[UnknownSymbol, Vine][FullName]
 * Full name:        Missing[UnknownSymbol, YouTube][FullName]
 *
 * Usage:            {Missing[UnknownSymbol, BingMaps][Usage], Missing[UnknownSymbol, DeviantArt][Usage], Missing[UnknownSymbol, EsriMap][Usage], Missing[UnknownSymbol, GoogleDocs][Usage], Missing[UnknownSymbol, GoogleForms][Usage], Missing[UnknownSymbol, GoogleMaps][Usage], Missing[UnknownSymbol, GoogleSheets][Usage], Missing[UnknownSymbol, GoogleSlides][Usage], Missing[UnknownSymbol, Imgur][Usage], Missing[UnknownSymbol, Instagram][Usage], Missing[UnknownSymbol, OpenStreetMap][Usage], Missing[UnknownSymbol, Reddit][Usage], Missing[UnknownSymbol, SoundCloud][Usage], Missing[UnknownSymbol, Twitter][Usage], Missing[UnknownSymbol, UStream][Usage], Missing[UnknownSymbol, Vimeo][Usage], Missing[UnknownSymbol, Vine][Usage], Missing[UnknownSymbol, YouTube][Usage]}
 *
 *                   Missing[UnknownSymbol, BingMaps][Options]
 *                   Missing[UnknownSymbol, DeviantArt][Options]
 *                   Missing[UnknownSymbol, EsriMap][Options]
 *                   Missing[UnknownSymbol, GoogleDocs][Options]
 *                   Missing[UnknownSymbol, GoogleForms][Options]
 *                   Missing[UnknownSymbol, GoogleMaps][Options]
 *                   Missing[UnknownSymbol, GoogleSheets][Options]
 *                   Missing[UnknownSymbol, GoogleSlides][Options]
 *                   Missing[UnknownSymbol, Imgur][Options]
 *                   Missing[UnknownSymbol, Instagram][Options]
 *                   Missing[UnknownSymbol, OpenStreetMap][Options]
 *                   Missing[UnknownSymbol, Reddit][Options]
 *                   Missing[UnknownSymbol, SoundCloud][Options]
 *                   Missing[UnknownSymbol, Twitter][Options]
 *                   Missing[UnknownSymbol, UStream][Options]
 *                   Missing[UnknownSymbol, Vimeo][Options]
 *                   Missing[UnknownSymbol, Vine][Options]
 * Options:          Missing[UnknownSymbol, YouTube][Options]
 *
 *                   Missing[UnknownSymbol, BingMaps][Attributes]
 *                   Missing[UnknownSymbol, DeviantArt][Attributes]
 *                   Missing[UnknownSymbol, EsriMap][Attributes]
 *                   Missing[UnknownSymbol, GoogleDocs][Attributes]
 *                   Missing[UnknownSymbol, GoogleForms][Attributes]
 *                   Missing[UnknownSymbol, GoogleMaps][Attributes]
 *                   Missing[UnknownSymbol, GoogleSheets][Attributes]
 *                   Missing[UnknownSymbol, GoogleSlides][Attributes]
 *                   Missing[UnknownSymbol, Imgur][Attributes]
 *                   Missing[UnknownSymbol, Instagram][Attributes]
 *                   Missing[UnknownSymbol, OpenStreetMap][Attributes]
 *                   Missing[UnknownSymbol, Reddit][Attributes]
 *                   Missing[UnknownSymbol, SoundCloud][Attributes]
 *                   Missing[UnknownSymbol, Twitter][Attributes]
 *                   Missing[UnknownSymbol, UStream][Attributes]
 *                   Missing[UnknownSymbol, Vimeo][Attributes]
 *                   Missing[UnknownSymbol, Vine][Attributes]
 * Attributes:       Missing[UnknownSymbol, YouTube][Attributes]
 *
 *                   local: <>{Missing[UnknownSymbol, BingMaps][Documentation], Missing[UnknownSymbol, DeviantArt][Documentation], Missing[UnknownSymbol, EsriMap][Documentation], Missing[UnknownSymbol, GoogleDocs][Documentation], Missing[UnknownSymbol, GoogleForms][Documentation], Missing[UnknownSymbol, GoogleMaps][Documentation], Missing[UnknownSymbol, GoogleSheets][Documentation], Missing[UnknownSymbol, GoogleSlides][Documentation], Missing[UnknownSymbol, Imgur][Documentation], Missing[UnknownSymbol, Instagram][Documentation], Missing[UnknownSymbol, OpenStreetMap][Documentation], Missing[UnknownSymbol, Reddit][Documentation], Missing[UnknownSymbol, SoundCloud][Documentation], Missing[UnknownSymbol, Twitter][Documentation], Missing[UnknownSymbol, UStream][Documentation], Missing[UnknownSymbol, Vimeo][Documentation], Missing[UnknownSymbol, Vine][Documentation], Missing[UnknownSymbol, YouTube][Documentation]}[Local]
 * Documentation:    web: <>{Missing[UnknownSymbol, BingMaps][Documentation], Missing[UnknownSymbol, DeviantArt][Documentation], Missing[UnknownSymbol, EsriMap][Documentation], Missing[UnknownSymbol, GoogleDocs][Documentation], Missing[UnknownSymbol, GoogleForms][Documentation], Missing[UnknownSymbol, GoogleMaps][Documentation], Missing[UnknownSymbol, GoogleSheets][Documentation], Missing[UnknownSymbol, GoogleSlides][Documentation], Missing[UnknownSymbol, Imgur][Documentation], Missing[UnknownSymbol, Instagram][Documentation], Missing[UnknownSymbol, OpenStreetMap][Documentation], Missing[UnknownSymbol, Reddit][Documentation], Missing[UnknownSymbol, SoundCloud][Documentation], Missing[UnknownSymbol, Twitter][Documentation], Missing[UnknownSymbol, UStream][Documentation], Missing[UnknownSymbol, Vimeo][Documentation], Missing[UnknownSymbol, Vine][Documentation], Missing[UnknownSymbol, YouTube][Documentation]}[Web]
 *
 *                   Missing[UnknownSymbol, BingMaps][Definitions]
 *                   Missing[UnknownSymbol, DeviantArt][Definitions]
 *                   Missing[UnknownSymbol, EsriMap][Definitions]
 *                   Missing[UnknownSymbol, GoogleDocs][Definitions]
 *                   Missing[UnknownSymbol, GoogleForms][Definitions]
 *                   Missing[UnknownSymbol, GoogleMaps][Definitions]
 *                   Missing[UnknownSymbol, GoogleSheets][Definitions]
 *                   Missing[UnknownSymbol, GoogleSlides][Definitions]
 *                   Missing[UnknownSymbol, Imgur][Definitions]
 *                   Missing[UnknownSymbol, Instagram][Definitions]
 *                   Missing[UnknownSymbol, OpenStreetMap][Definitions]
 *                   Missing[UnknownSymbol, Reddit][Definitions]
 *                   Missing[UnknownSymbol, SoundCloud][Definitions]
 *                   Missing[UnknownSymbol, Twitter][Definitions]
 *                   Missing[UnknownSymbol, UStream][Definitions]
 *                   Missing[UnknownSymbol, Vimeo][Definitions]
 *                   Missing[UnknownSymbol, Vine][Definitions]
 * Definitions:      Missing[UnknownSymbol, YouTube][Definitions]
 *
 *                   Missing[UnknownSymbol, BingMaps][OwnValues]
 *                   Missing[UnknownSymbol, DeviantArt][OwnValues]
 *                   Missing[UnknownSymbol, EsriMap][OwnValues]
 *                   Missing[UnknownSymbol, GoogleDocs][OwnValues]
 *                   Missing[UnknownSymbol, GoogleForms][OwnValues]
 *                   Missing[UnknownSymbol, GoogleMaps][OwnValues]
 *                   Missing[UnknownSymbol, GoogleSheets][OwnValues]
 *                   Missing[UnknownSymbol, GoogleSlides][OwnValues]
 *                   Missing[UnknownSymbol, Imgur][OwnValues]
 *                   Missing[UnknownSymbol, Instagram][OwnValues]
 *                   Missing[UnknownSymbol, OpenStreetMap][OwnValues]
 *                   Missing[UnknownSymbol, Reddit][OwnValues]
 *                   Missing[UnknownSymbol, SoundCloud][OwnValues]
 *                   Missing[UnknownSymbol, Twitter][OwnValues]
 *                   Missing[UnknownSymbol, UStream][OwnValues]
 *                   Missing[UnknownSymbol, Vimeo][OwnValues]
 *                   Missing[UnknownSymbol, Vine][OwnValues]
 * Own values:       Missing[UnknownSymbol, YouTube][OwnValues]
 *
 *                   Missing[UnknownSymbol, BingMaps][DownValues]
 *                   Missing[UnknownSymbol, DeviantArt][DownValues]
 *                   Missing[UnknownSymbol, EsriMap][DownValues]
 *                   Missing[UnknownSymbol, GoogleDocs][DownValues]
 *                   Missing[UnknownSymbol, GoogleForms][DownValues]
 *                   Missing[UnknownSymbol, GoogleMaps][DownValues]
 *                   Missing[UnknownSymbol, GoogleSheets][DownValues]
 *                   Missing[UnknownSymbol, GoogleSlides][DownValues]
 *                   Missing[UnknownSymbol, Imgur][DownValues]
 *                   Missing[UnknownSymbol, Instagram][DownValues]
 *                   Missing[UnknownSymbol, OpenStreetMap][DownValues]
 *                   Missing[UnknownSymbol, Reddit][DownValues]
 *                   Missing[UnknownSymbol, SoundCloud][DownValues]
 *                   Missing[UnknownSymbol, Twitter][DownValues]
 *                   Missing[UnknownSymbol, UStream][DownValues]
 *                   Missing[UnknownSymbol, Vimeo][DownValues]
 *                   Missing[UnknownSymbol, Vine][DownValues]
 * Down values:      Missing[UnknownSymbol, YouTube][DownValues]
 *
 *                   Missing[UnknownSymbol, BingMaps][UpValues]
 *                   Missing[UnknownSymbol, DeviantArt][UpValues]
 *                   Missing[UnknownSymbol, EsriMap][UpValues]
 *                   Missing[UnknownSymbol, GoogleDocs][UpValues]
 *                   Missing[UnknownSymbol, GoogleForms][UpValues]
 *                   Missing[UnknownSymbol, GoogleMaps][UpValues]
 *                   Missing[UnknownSymbol, GoogleSheets][UpValues]
 *                   Missing[UnknownSymbol, GoogleSlides][UpValues]
 *                   Missing[UnknownSymbol, Imgur][UpValues]
 *                   Missing[UnknownSymbol, Instagram][UpValues]
 *                   Missing[UnknownSymbol, OpenStreetMap][UpValues]
 *                   Missing[UnknownSymbol, Reddit][UpValues]
 *                   Missing[UnknownSymbol, SoundCloud][UpValues]
 *                   Missing[UnknownSymbol, Twitter][UpValues]
 *                   Missing[UnknownSymbol, UStream][UpValues]
 *                   Missing[UnknownSymbol, Vimeo][UpValues]
 *                   Missing[UnknownSymbol, Vine][UpValues]
 * Up values:        Missing[UnknownSymbol, YouTube][UpValues]
 *
 *                   Missing[UnknownSymbol, BingMaps][SubValues]
 *                   Missing[UnknownSymbol, DeviantArt][SubValues]
 *                   Missing[UnknownSymbol, EsriMap][SubValues]
 *                   Missing[UnknownSymbol, GoogleDocs][SubValues]
 *                   Missing[UnknownSymbol, GoogleForms][SubValues]
 *                   Missing[UnknownSymbol, GoogleMaps][SubValues]
 *                   Missing[UnknownSymbol, GoogleSheets][SubValues]
 *                   Missing[UnknownSymbol, GoogleSlides][SubValues]
 *                   Missing[UnknownSymbol, Imgur][SubValues]
 *                   Missing[UnknownSymbol, Instagram][SubValues]
 *                   Missing[UnknownSymbol, OpenStreetMap][SubValues]
 *                   Missing[UnknownSymbol, Reddit][SubValues]
 *                   Missing[UnknownSymbol, SoundCloud][SubValues]
 *                   Missing[UnknownSymbol, Twitter][SubValues]
 *                   Missing[UnknownSymbol, UStream][SubValues]
 *                   Missing[UnknownSymbol, Vimeo][SubValues]
 *                   Missing[UnknownSymbol, Vine][SubValues]
 * Sub values:       Missing[UnknownSymbol, YouTube][SubValues]
 *
 *                   Missing[UnknownSymbol, BingMaps][DefaultValues]
 *                   Missing[UnknownSymbol, DeviantArt][DefaultValues]
 *                   Missing[UnknownSymbol, EsriMap][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleDocs][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleForms][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleMaps][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleSheets][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleSlides][DefaultValues]
 *                   Missing[UnknownSymbol, Imgur][DefaultValues]
 *                   Missing[UnknownSymbol, Instagram][DefaultValues]
 *                   Missing[UnknownSymbol, OpenStreetMap][DefaultValues]
 *                   Missing[UnknownSymbol, Reddit][DefaultValues]
 *                   Missing[UnknownSymbol, SoundCloud][DefaultValues]
 *                   Missing[UnknownSymbol, Twitter][DefaultValues]
 *                   Missing[UnknownSymbol, UStream][DefaultValues]
 *                   Missing[UnknownSymbol, Vimeo][DefaultValues]
 *                   Missing[UnknownSymbol, Vine][DefaultValues]
 * Default value:    Missing[UnknownSymbol, YouTube][DefaultValues]
 *
 *                   Missing[UnknownSymbol, BingMaps][NValues]
 *                   Missing[UnknownSymbol, DeviantArt][NValues]
 *                   Missing[UnknownSymbol, EsriMap][NValues]
 *                   Missing[UnknownSymbol, GoogleDocs][NValues]
 *                   Missing[UnknownSymbol, GoogleForms][NValues]
 *                   Missing[UnknownSymbol, GoogleMaps][NValues]
 *                   Missing[UnknownSymbol, GoogleSheets][NValues]
 *                   Missing[UnknownSymbol, GoogleSlides][NValues]
 *                   Missing[UnknownSymbol, Imgur][NValues]
 *                   Missing[UnknownSymbol, Instagram][NValues]
 *                   Missing[UnknownSymbol, OpenStreetMap][NValues]
 *                   Missing[UnknownSymbol, Reddit][NValues]
 *                   Missing[UnknownSymbol, SoundCloud][NValues]
 *                   Missing[UnknownSymbol, Twitter][NValues]
 *                   Missing[UnknownSymbol, UStream][NValues]
 *                   Missing[UnknownSymbol, Vimeo][NValues]
 *                   Missing[UnknownSymbol, Vine][NValues]
 * Numeric values:   Missing[UnknownSymbol, YouTube][NValues]
 */
fun `$EmbeddableServices`(vararg arguments: Any?, options: MutableMap<String, Any?> = mutableMapOf()): MathematicaFunction {
	return MathematicaFunction("\$EmbeddableServices", arguments.toMutableList(), options)
}
