package com.daniloaraujosilva.mathemagika.library.jvm.functions

import com.daniloaraujosilva.mathemagika.library.jvm.MathematicaFunction

/**
 *````
 *
 *                   ArXivID
 *                   CASRegistryNumber
 *                   ChEBIID
 *                   ChEMBLID
 *                   ChemSpiderID
 *                   DOI
 *                   DrugBankID
 *                   GNDID
 *                   InChI
 *                   InChIKey
 *                   ISAN
 *                   ISBN10
 *                   ISBN13
 *                   ISMN
 *                   ISNI
 *                   ISRC
 *                   ISSN
 *                   ISWC
 *                   KEGGID
 *                   LibraryOfCongressAuthorityID
 *                   LibraryOfCongressControlNumber
 *                   MeSHCode
 *                   MeSHConceptID
 *                   MeSHDescriptorID
 *                   MeSHTermID
 *                   MusicBrainzAreaID
 *                   MusicBrainzArtistID
 *                   MusicBrainzEventID
 *                   MusicBrainzInstrumentID
 *                   MusicBrainzLabelID
 *                   MusicBrainzPlaceID
 *                   MusicBrainzRecordingID
 *                   MusicBrainzReleaseGroupID
 *                   MusicBrainzReleaseID
 *                   MusicBrainzSeriesID
 *                   MusicBrainzWorkID
 *                   OCLCControlNumber
 *                   OCLCWorkID
 *                   OpenCitationsBibliographicResourceID
 *                   ORCIDID
 *                   OSMRelationID
 *                   PDBStructureID
 *                   PubChemBioAssayID
 *                   PubChemCompoundID
 *                   PubChemSubstanceID
 *                   PubMedCentralID
 *                   PubMedID
 *                   VIAFID
 * Name:             WikidataID
 *
 *                   Missing[UnknownSymbol, ArXivID][FullName]
 *                   Missing[UnknownSymbol, CASRegistryNumber][FullName]
 *                   Missing[UnknownSymbol, ChEBIID][FullName]
 *                   Missing[UnknownSymbol, ChEMBLID][FullName]
 *                   Missing[UnknownSymbol, ChemSpiderID][FullName]
 *                   Missing[UnknownSymbol, DOI][FullName]
 *                   Missing[UnknownSymbol, DrugBankID][FullName]
 *                   Missing[UnknownSymbol, GNDID][FullName]
 *                   Missing[UnknownSymbol, InChI][FullName]
 *                   Missing[UnknownSymbol, InChIKey][FullName]
 *                   Missing[UnknownSymbol, ISAN][FullName]
 *                   Missing[UnknownSymbol, ISBN10][FullName]
 *                   Missing[UnknownSymbol, ISBN13][FullName]
 *                   Missing[UnknownSymbol, ISMN][FullName]
 *                   Missing[UnknownSymbol, ISNI][FullName]
 *                   Missing[UnknownSymbol, ISRC][FullName]
 *                   Missing[UnknownSymbol, ISSN][FullName]
 *                   Missing[UnknownSymbol, ISWC][FullName]
 *                   Missing[UnknownSymbol, KEGGID][FullName]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][FullName]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][FullName]
 *                   Missing[UnknownSymbol, MeSHCode][FullName]
 *                   Missing[UnknownSymbol, MeSHConceptID][FullName]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][FullName]
 *                   Missing[UnknownSymbol, MeSHTermID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][FullName]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][FullName]
 *                   Missing[UnknownSymbol, OCLCControlNumber][FullName]
 *                   Missing[UnknownSymbol, OCLCWorkID][FullName]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][FullName]
 *                   Missing[UnknownSymbol, ORCIDID][FullName]
 *                   Missing[UnknownSymbol, OSMRelationID][FullName]
 *                   Missing[UnknownSymbol, PDBStructureID][FullName]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][FullName]
 *                   Missing[UnknownSymbol, PubChemCompoundID][FullName]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][FullName]
 *                   Missing[UnknownSymbol, PubMedCentralID][FullName]
 *                   Missing[UnknownSymbol, PubMedID][FullName]
 *                   Missing[UnknownSymbol, VIAFID][FullName]
 * Full name:        Missing[UnknownSymbol, WikidataID][FullName]
 *
 * Usage:            {Missing[UnknownSymbol, ArXivID][Usage], Missing[UnknownSymbol, CASRegistryNumber][Usage], Missing[UnknownSymbol, ChEBIID][Usage], Missing[UnknownSymbol, ChEMBLID][Usage], Missing[UnknownSymbol, ChemSpiderID][Usage], Missing[UnknownSymbol, DOI][Usage], Missing[UnknownSymbol, DrugBankID][Usage], Missing[UnknownSymbol, GNDID][Usage], Missing[UnknownSymbol, InChI][Usage], Missing[UnknownSymbol, InChIKey][Usage], Missing[UnknownSymbol, ISAN][Usage], Missing[UnknownSymbol, ISBN10][Usage], Missing[UnknownSymbol, ISBN13][Usage], Missing[UnknownSymbol, ISMN][Usage], Missing[UnknownSymbol, ISNI][Usage], Missing[UnknownSymbol, ISRC][Usage], Missing[UnknownSymbol, ISSN][Usage], Missing[UnknownSymbol, ISWC][Usage], Missing[UnknownSymbol, KEGGID][Usage], Missing[UnknownSymbol, LibraryOfCongressAuthorityID][Usage], Missing[UnknownSymbol, LibraryOfCongressControlNumber][Usage], Missing[UnknownSymbol, MeSHCode][Usage], Missing[UnknownSymbol, MeSHConceptID][Usage], Missing[UnknownSymbol, MeSHDescriptorID][Usage], Missing[UnknownSymbol, MeSHTermID][Usage], Missing[UnknownSymbol, MusicBrainzAreaID][Usage], Missing[UnknownSymbol, MusicBrainzArtistID][Usage], Missing[UnknownSymbol, MusicBrainzEventID][Usage], Missing[UnknownSymbol, MusicBrainzInstrumentID][Usage], Missing[UnknownSymbol, MusicBrainzLabelID][Usage], Missing[UnknownSymbol, MusicBrainzPlaceID][Usage], Missing[UnknownSymbol, MusicBrainzRecordingID][Usage], Missing[UnknownSymbol, MusicBrainzReleaseGroupID][Usage], Missing[UnknownSymbol, MusicBrainzReleaseID][Usage], Missing[UnknownSymbol, MusicBrainzSeriesID][Usage], Missing[UnknownSymbol, MusicBrainzWorkID][Usage], Missing[UnknownSymbol, OCLCControlNumber][Usage], Missing[UnknownSymbol, OCLCWorkID][Usage], Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][Usage], Missing[UnknownSymbol, ORCIDID][Usage], Missing[UnknownSymbol, OSMRelationID][Usage], Missing[UnknownSymbol, PDBStructureID][Usage], Missing[UnknownSymbol, PubChemBioAssayID][Usage], Missing[UnknownSymbol, PubChemCompoundID][Usage], Missing[UnknownSymbol, PubChemSubstanceID][Usage], Missing[UnknownSymbol, PubMedCentralID][Usage], Missing[UnknownSymbol, PubMedID][Usage], Missing[UnknownSymbol, VIAFID][Usage], Missing[UnknownSymbol, WikidataID][Usage]}
 *
 *                   Missing[UnknownSymbol, ArXivID][Options]
 *                   Missing[UnknownSymbol, CASRegistryNumber][Options]
 *                   Missing[UnknownSymbol, ChEBIID][Options]
 *                   Missing[UnknownSymbol, ChEMBLID][Options]
 *                   Missing[UnknownSymbol, ChemSpiderID][Options]
 *                   Missing[UnknownSymbol, DOI][Options]
 *                   Missing[UnknownSymbol, DrugBankID][Options]
 *                   Missing[UnknownSymbol, GNDID][Options]
 *                   Missing[UnknownSymbol, InChI][Options]
 *                   Missing[UnknownSymbol, InChIKey][Options]
 *                   Missing[UnknownSymbol, ISAN][Options]
 *                   Missing[UnknownSymbol, ISBN10][Options]
 *                   Missing[UnknownSymbol, ISBN13][Options]
 *                   Missing[UnknownSymbol, ISMN][Options]
 *                   Missing[UnknownSymbol, ISNI][Options]
 *                   Missing[UnknownSymbol, ISRC][Options]
 *                   Missing[UnknownSymbol, ISSN][Options]
 *                   Missing[UnknownSymbol, ISWC][Options]
 *                   Missing[UnknownSymbol, KEGGID][Options]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][Options]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][Options]
 *                   Missing[UnknownSymbol, MeSHCode][Options]
 *                   Missing[UnknownSymbol, MeSHConceptID][Options]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][Options]
 *                   Missing[UnknownSymbol, MeSHTermID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][Options]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][Options]
 *                   Missing[UnknownSymbol, OCLCControlNumber][Options]
 *                   Missing[UnknownSymbol, OCLCWorkID][Options]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][Options]
 *                   Missing[UnknownSymbol, ORCIDID][Options]
 *                   Missing[UnknownSymbol, OSMRelationID][Options]
 *                   Missing[UnknownSymbol, PDBStructureID][Options]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][Options]
 *                   Missing[UnknownSymbol, PubChemCompoundID][Options]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][Options]
 *                   Missing[UnknownSymbol, PubMedCentralID][Options]
 *                   Missing[UnknownSymbol, PubMedID][Options]
 *                   Missing[UnknownSymbol, VIAFID][Options]
 * Options:          Missing[UnknownSymbol, WikidataID][Options]
 *
 *                   Missing[UnknownSymbol, ArXivID][Attributes]
 *                   Missing[UnknownSymbol, CASRegistryNumber][Attributes]
 *                   Missing[UnknownSymbol, ChEBIID][Attributes]
 *                   Missing[UnknownSymbol, ChEMBLID][Attributes]
 *                   Missing[UnknownSymbol, ChemSpiderID][Attributes]
 *                   Missing[UnknownSymbol, DOI][Attributes]
 *                   Missing[UnknownSymbol, DrugBankID][Attributes]
 *                   Missing[UnknownSymbol, GNDID][Attributes]
 *                   Missing[UnknownSymbol, InChI][Attributes]
 *                   Missing[UnknownSymbol, InChIKey][Attributes]
 *                   Missing[UnknownSymbol, ISAN][Attributes]
 *                   Missing[UnknownSymbol, ISBN10][Attributes]
 *                   Missing[UnknownSymbol, ISBN13][Attributes]
 *                   Missing[UnknownSymbol, ISMN][Attributes]
 *                   Missing[UnknownSymbol, ISNI][Attributes]
 *                   Missing[UnknownSymbol, ISRC][Attributes]
 *                   Missing[UnknownSymbol, ISSN][Attributes]
 *                   Missing[UnknownSymbol, ISWC][Attributes]
 *                   Missing[UnknownSymbol, KEGGID][Attributes]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][Attributes]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][Attributes]
 *                   Missing[UnknownSymbol, MeSHCode][Attributes]
 *                   Missing[UnknownSymbol, MeSHConceptID][Attributes]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][Attributes]
 *                   Missing[UnknownSymbol, MeSHTermID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][Attributes]
 *                   Missing[UnknownSymbol, OCLCControlNumber][Attributes]
 *                   Missing[UnknownSymbol, OCLCWorkID][Attributes]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][Attributes]
 *                   Missing[UnknownSymbol, ORCIDID][Attributes]
 *                   Missing[UnknownSymbol, OSMRelationID][Attributes]
 *                   Missing[UnknownSymbol, PDBStructureID][Attributes]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][Attributes]
 *                   Missing[UnknownSymbol, PubChemCompoundID][Attributes]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][Attributes]
 *                   Missing[UnknownSymbol, PubMedCentralID][Attributes]
 *                   Missing[UnknownSymbol, PubMedID][Attributes]
 *                   Missing[UnknownSymbol, VIAFID][Attributes]
 * Attributes:       Missing[UnknownSymbol, WikidataID][Attributes]
 *
 *                   local: <>{Missing[UnknownSymbol, ArXivID][Documentation], Missing[UnknownSymbol, CASRegistryNumber][Documentation], Missing[UnknownSymbol, ChEBIID][Documentation], Missing[UnknownSymbol, ChEMBLID][Documentation], Missing[UnknownSymbol, ChemSpiderID][Documentation], Missing[UnknownSymbol, DOI][Documentation], Missing[UnknownSymbol, DrugBankID][Documentation], Missing[UnknownSymbol, GNDID][Documentation], Missing[UnknownSymbol, InChI][Documentation], Missing[UnknownSymbol, InChIKey][Documentation], Missing[UnknownSymbol, ISAN][Documentation], Missing[UnknownSymbol, ISBN10][Documentation], Missing[UnknownSymbol, ISBN13][Documentation], Missing[UnknownSymbol, ISMN][Documentation], Missing[UnknownSymbol, ISNI][Documentation], Missing[UnknownSymbol, ISRC][Documentation], Missing[UnknownSymbol, ISSN][Documentation], Missing[UnknownSymbol, ISWC][Documentation], Missing[UnknownSymbol, KEGGID][Documentation], Missing[UnknownSymbol, LibraryOfCongressAuthorityID][Documentation], Missing[UnknownSymbol, LibraryOfCongressControlNumber][Documentation], Missing[UnknownSymbol, MeSHCode][Documentation], Missing[UnknownSymbol, MeSHConceptID][Documentation], Missing[UnknownSymbol, MeSHDescriptorID][Documentation], Missing[UnknownSymbol, MeSHTermID][Documentation], Missing[UnknownSymbol, MusicBrainzAreaID][Documentation], Missing[UnknownSymbol, MusicBrainzArtistID][Documentation], Missing[UnknownSymbol, MusicBrainzEventID][Documentation], Missing[UnknownSymbol, MusicBrainzInstrumentID][Documentation], Missing[UnknownSymbol, MusicBrainzLabelID][Documentation], Missing[UnknownSymbol, MusicBrainzPlaceID][Documentation], Missing[UnknownSymbol, MusicBrainzRecordingID][Documentation], Missing[UnknownSymbol, MusicBrainzReleaseGroupID][Documentation], Missing[UnknownSymbol, MusicBrainzReleaseID][Documentation], Missing[UnknownSymbol, MusicBrainzSeriesID][Documentation], Missing[UnknownSymbol, MusicBrainzWorkID][Documentation], Missing[UnknownSymbol, OCLCControlNumber][Documentation], Missing[UnknownSymbol, OCLCWorkID][Documentation], Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][Documentation], Missing[UnknownSymbol, ORCIDID][Documentation], Missing[UnknownSymbol, OSMRelationID][Documentation], Missing[UnknownSymbol, PDBStructureID][Documentation], Missing[UnknownSymbol, PubChemBioAssayID][Documentation], Missing[UnknownSymbol, PubChemCompoundID][Documentation], Missing[UnknownSymbol, PubChemSubstanceID][Documentation], Missing[UnknownSymbol, PubMedCentralID][Documentation], Missing[UnknownSymbol, PubMedID][Documentation], Missing[UnknownSymbol, VIAFID][Documentation], Missing[UnknownSymbol, WikidataID][Documentation]}[Local]
 * Documentation:    web: <>{Missing[UnknownSymbol, ArXivID][Documentation], Missing[UnknownSymbol, CASRegistryNumber][Documentation], Missing[UnknownSymbol, ChEBIID][Documentation], Missing[UnknownSymbol, ChEMBLID][Documentation], Missing[UnknownSymbol, ChemSpiderID][Documentation], Missing[UnknownSymbol, DOI][Documentation], Missing[UnknownSymbol, DrugBankID][Documentation], Missing[UnknownSymbol, GNDID][Documentation], Missing[UnknownSymbol, InChI][Documentation], Missing[UnknownSymbol, InChIKey][Documentation], Missing[UnknownSymbol, ISAN][Documentation], Missing[UnknownSymbol, ISBN10][Documentation], Missing[UnknownSymbol, ISBN13][Documentation], Missing[UnknownSymbol, ISMN][Documentation], Missing[UnknownSymbol, ISNI][Documentation], Missing[UnknownSymbol, ISRC][Documentation], Missing[UnknownSymbol, ISSN][Documentation], Missing[UnknownSymbol, ISWC][Documentation], Missing[UnknownSymbol, KEGGID][Documentation], Missing[UnknownSymbol, LibraryOfCongressAuthorityID][Documentation], Missing[UnknownSymbol, LibraryOfCongressControlNumber][Documentation], Missing[UnknownSymbol, MeSHCode][Documentation], Missing[UnknownSymbol, MeSHConceptID][Documentation], Missing[UnknownSymbol, MeSHDescriptorID][Documentation], Missing[UnknownSymbol, MeSHTermID][Documentation], Missing[UnknownSymbol, MusicBrainzAreaID][Documentation], Missing[UnknownSymbol, MusicBrainzArtistID][Documentation], Missing[UnknownSymbol, MusicBrainzEventID][Documentation], Missing[UnknownSymbol, MusicBrainzInstrumentID][Documentation], Missing[UnknownSymbol, MusicBrainzLabelID][Documentation], Missing[UnknownSymbol, MusicBrainzPlaceID][Documentation], Missing[UnknownSymbol, MusicBrainzRecordingID][Documentation], Missing[UnknownSymbol, MusicBrainzReleaseGroupID][Documentation], Missing[UnknownSymbol, MusicBrainzReleaseID][Documentation], Missing[UnknownSymbol, MusicBrainzSeriesID][Documentation], Missing[UnknownSymbol, MusicBrainzWorkID][Documentation], Missing[UnknownSymbol, OCLCControlNumber][Documentation], Missing[UnknownSymbol, OCLCWorkID][Documentation], Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][Documentation], Missing[UnknownSymbol, ORCIDID][Documentation], Missing[UnknownSymbol, OSMRelationID][Documentation], Missing[UnknownSymbol, PDBStructureID][Documentation], Missing[UnknownSymbol, PubChemBioAssayID][Documentation], Missing[UnknownSymbol, PubChemCompoundID][Documentation], Missing[UnknownSymbol, PubChemSubstanceID][Documentation], Missing[UnknownSymbol, PubMedCentralID][Documentation], Missing[UnknownSymbol, PubMedID][Documentation], Missing[UnknownSymbol, VIAFID][Documentation], Missing[UnknownSymbol, WikidataID][Documentation]}[Web]
 *
 *                   Missing[UnknownSymbol, ArXivID][Definitions]
 *                   Missing[UnknownSymbol, CASRegistryNumber][Definitions]
 *                   Missing[UnknownSymbol, ChEBIID][Definitions]
 *                   Missing[UnknownSymbol, ChEMBLID][Definitions]
 *                   Missing[UnknownSymbol, ChemSpiderID][Definitions]
 *                   Missing[UnknownSymbol, DOI][Definitions]
 *                   Missing[UnknownSymbol, DrugBankID][Definitions]
 *                   Missing[UnknownSymbol, GNDID][Definitions]
 *                   Missing[UnknownSymbol, InChI][Definitions]
 *                   Missing[UnknownSymbol, InChIKey][Definitions]
 *                   Missing[UnknownSymbol, ISAN][Definitions]
 *                   Missing[UnknownSymbol, ISBN10][Definitions]
 *                   Missing[UnknownSymbol, ISBN13][Definitions]
 *                   Missing[UnknownSymbol, ISMN][Definitions]
 *                   Missing[UnknownSymbol, ISNI][Definitions]
 *                   Missing[UnknownSymbol, ISRC][Definitions]
 *                   Missing[UnknownSymbol, ISSN][Definitions]
 *                   Missing[UnknownSymbol, ISWC][Definitions]
 *                   Missing[UnknownSymbol, KEGGID][Definitions]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][Definitions]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][Definitions]
 *                   Missing[UnknownSymbol, MeSHCode][Definitions]
 *                   Missing[UnknownSymbol, MeSHConceptID][Definitions]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][Definitions]
 *                   Missing[UnknownSymbol, MeSHTermID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][Definitions]
 *                   Missing[UnknownSymbol, OCLCControlNumber][Definitions]
 *                   Missing[UnknownSymbol, OCLCWorkID][Definitions]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][Definitions]
 *                   Missing[UnknownSymbol, ORCIDID][Definitions]
 *                   Missing[UnknownSymbol, OSMRelationID][Definitions]
 *                   Missing[UnknownSymbol, PDBStructureID][Definitions]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][Definitions]
 *                   Missing[UnknownSymbol, PubChemCompoundID][Definitions]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][Definitions]
 *                   Missing[UnknownSymbol, PubMedCentralID][Definitions]
 *                   Missing[UnknownSymbol, PubMedID][Definitions]
 *                   Missing[UnknownSymbol, VIAFID][Definitions]
 * Definitions:      Missing[UnknownSymbol, WikidataID][Definitions]
 *
 *                   Missing[UnknownSymbol, ArXivID][OwnValues]
 *                   Missing[UnknownSymbol, CASRegistryNumber][OwnValues]
 *                   Missing[UnknownSymbol, ChEBIID][OwnValues]
 *                   Missing[UnknownSymbol, ChEMBLID][OwnValues]
 *                   Missing[UnknownSymbol, ChemSpiderID][OwnValues]
 *                   Missing[UnknownSymbol, DOI][OwnValues]
 *                   Missing[UnknownSymbol, DrugBankID][OwnValues]
 *                   Missing[UnknownSymbol, GNDID][OwnValues]
 *                   Missing[UnknownSymbol, InChI][OwnValues]
 *                   Missing[UnknownSymbol, InChIKey][OwnValues]
 *                   Missing[UnknownSymbol, ISAN][OwnValues]
 *                   Missing[UnknownSymbol, ISBN10][OwnValues]
 *                   Missing[UnknownSymbol, ISBN13][OwnValues]
 *                   Missing[UnknownSymbol, ISMN][OwnValues]
 *                   Missing[UnknownSymbol, ISNI][OwnValues]
 *                   Missing[UnknownSymbol, ISRC][OwnValues]
 *                   Missing[UnknownSymbol, ISSN][OwnValues]
 *                   Missing[UnknownSymbol, ISWC][OwnValues]
 *                   Missing[UnknownSymbol, KEGGID][OwnValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][OwnValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][OwnValues]
 *                   Missing[UnknownSymbol, MeSHCode][OwnValues]
 *                   Missing[UnknownSymbol, MeSHConceptID][OwnValues]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][OwnValues]
 *                   Missing[UnknownSymbol, MeSHTermID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][OwnValues]
 *                   Missing[UnknownSymbol, OCLCControlNumber][OwnValues]
 *                   Missing[UnknownSymbol, OCLCWorkID][OwnValues]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][OwnValues]
 *                   Missing[UnknownSymbol, ORCIDID][OwnValues]
 *                   Missing[UnknownSymbol, OSMRelationID][OwnValues]
 *                   Missing[UnknownSymbol, PDBStructureID][OwnValues]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][OwnValues]
 *                   Missing[UnknownSymbol, PubChemCompoundID][OwnValues]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][OwnValues]
 *                   Missing[UnknownSymbol, PubMedCentralID][OwnValues]
 *                   Missing[UnknownSymbol, PubMedID][OwnValues]
 *                   Missing[UnknownSymbol, VIAFID][OwnValues]
 * Own values:       Missing[UnknownSymbol, WikidataID][OwnValues]
 *
 *                   Missing[UnknownSymbol, ArXivID][DownValues]
 *                   Missing[UnknownSymbol, CASRegistryNumber][DownValues]
 *                   Missing[UnknownSymbol, ChEBIID][DownValues]
 *                   Missing[UnknownSymbol, ChEMBLID][DownValues]
 *                   Missing[UnknownSymbol, ChemSpiderID][DownValues]
 *                   Missing[UnknownSymbol, DOI][DownValues]
 *                   Missing[UnknownSymbol, DrugBankID][DownValues]
 *                   Missing[UnknownSymbol, GNDID][DownValues]
 *                   Missing[UnknownSymbol, InChI][DownValues]
 *                   Missing[UnknownSymbol, InChIKey][DownValues]
 *                   Missing[UnknownSymbol, ISAN][DownValues]
 *                   Missing[UnknownSymbol, ISBN10][DownValues]
 *                   Missing[UnknownSymbol, ISBN13][DownValues]
 *                   Missing[UnknownSymbol, ISMN][DownValues]
 *                   Missing[UnknownSymbol, ISNI][DownValues]
 *                   Missing[UnknownSymbol, ISRC][DownValues]
 *                   Missing[UnknownSymbol, ISSN][DownValues]
 *                   Missing[UnknownSymbol, ISWC][DownValues]
 *                   Missing[UnknownSymbol, KEGGID][DownValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][DownValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][DownValues]
 *                   Missing[UnknownSymbol, MeSHCode][DownValues]
 *                   Missing[UnknownSymbol, MeSHConceptID][DownValues]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][DownValues]
 *                   Missing[UnknownSymbol, MeSHTermID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][DownValues]
 *                   Missing[UnknownSymbol, OCLCControlNumber][DownValues]
 *                   Missing[UnknownSymbol, OCLCWorkID][DownValues]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][DownValues]
 *                   Missing[UnknownSymbol, ORCIDID][DownValues]
 *                   Missing[UnknownSymbol, OSMRelationID][DownValues]
 *                   Missing[UnknownSymbol, PDBStructureID][DownValues]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][DownValues]
 *                   Missing[UnknownSymbol, PubChemCompoundID][DownValues]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][DownValues]
 *                   Missing[UnknownSymbol, PubMedCentralID][DownValues]
 *                   Missing[UnknownSymbol, PubMedID][DownValues]
 *                   Missing[UnknownSymbol, VIAFID][DownValues]
 * Down values:      Missing[UnknownSymbol, WikidataID][DownValues]
 *
 *                   Missing[UnknownSymbol, ArXivID][UpValues]
 *                   Missing[UnknownSymbol, CASRegistryNumber][UpValues]
 *                   Missing[UnknownSymbol, ChEBIID][UpValues]
 *                   Missing[UnknownSymbol, ChEMBLID][UpValues]
 *                   Missing[UnknownSymbol, ChemSpiderID][UpValues]
 *                   Missing[UnknownSymbol, DOI][UpValues]
 *                   Missing[UnknownSymbol, DrugBankID][UpValues]
 *                   Missing[UnknownSymbol, GNDID][UpValues]
 *                   Missing[UnknownSymbol, InChI][UpValues]
 *                   Missing[UnknownSymbol, InChIKey][UpValues]
 *                   Missing[UnknownSymbol, ISAN][UpValues]
 *                   Missing[UnknownSymbol, ISBN10][UpValues]
 *                   Missing[UnknownSymbol, ISBN13][UpValues]
 *                   Missing[UnknownSymbol, ISMN][UpValues]
 *                   Missing[UnknownSymbol, ISNI][UpValues]
 *                   Missing[UnknownSymbol, ISRC][UpValues]
 *                   Missing[UnknownSymbol, ISSN][UpValues]
 *                   Missing[UnknownSymbol, ISWC][UpValues]
 *                   Missing[UnknownSymbol, KEGGID][UpValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][UpValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][UpValues]
 *                   Missing[UnknownSymbol, MeSHCode][UpValues]
 *                   Missing[UnknownSymbol, MeSHConceptID][UpValues]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][UpValues]
 *                   Missing[UnknownSymbol, MeSHTermID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][UpValues]
 *                   Missing[UnknownSymbol, OCLCControlNumber][UpValues]
 *                   Missing[UnknownSymbol, OCLCWorkID][UpValues]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][UpValues]
 *                   Missing[UnknownSymbol, ORCIDID][UpValues]
 *                   Missing[UnknownSymbol, OSMRelationID][UpValues]
 *                   Missing[UnknownSymbol, PDBStructureID][UpValues]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][UpValues]
 *                   Missing[UnknownSymbol, PubChemCompoundID][UpValues]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][UpValues]
 *                   Missing[UnknownSymbol, PubMedCentralID][UpValues]
 *                   Missing[UnknownSymbol, PubMedID][UpValues]
 *                   Missing[UnknownSymbol, VIAFID][UpValues]
 * Up values:        Missing[UnknownSymbol, WikidataID][UpValues]
 *
 *                   Missing[UnknownSymbol, ArXivID][SubValues]
 *                   Missing[UnknownSymbol, CASRegistryNumber][SubValues]
 *                   Missing[UnknownSymbol, ChEBIID][SubValues]
 *                   Missing[UnknownSymbol, ChEMBLID][SubValues]
 *                   Missing[UnknownSymbol, ChemSpiderID][SubValues]
 *                   Missing[UnknownSymbol, DOI][SubValues]
 *                   Missing[UnknownSymbol, DrugBankID][SubValues]
 *                   Missing[UnknownSymbol, GNDID][SubValues]
 *                   Missing[UnknownSymbol, InChI][SubValues]
 *                   Missing[UnknownSymbol, InChIKey][SubValues]
 *                   Missing[UnknownSymbol, ISAN][SubValues]
 *                   Missing[UnknownSymbol, ISBN10][SubValues]
 *                   Missing[UnknownSymbol, ISBN13][SubValues]
 *                   Missing[UnknownSymbol, ISMN][SubValues]
 *                   Missing[UnknownSymbol, ISNI][SubValues]
 *                   Missing[UnknownSymbol, ISRC][SubValues]
 *                   Missing[UnknownSymbol, ISSN][SubValues]
 *                   Missing[UnknownSymbol, ISWC][SubValues]
 *                   Missing[UnknownSymbol, KEGGID][SubValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][SubValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][SubValues]
 *                   Missing[UnknownSymbol, MeSHCode][SubValues]
 *                   Missing[UnknownSymbol, MeSHConceptID][SubValues]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][SubValues]
 *                   Missing[UnknownSymbol, MeSHTermID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][SubValues]
 *                   Missing[UnknownSymbol, OCLCControlNumber][SubValues]
 *                   Missing[UnknownSymbol, OCLCWorkID][SubValues]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][SubValues]
 *                   Missing[UnknownSymbol, ORCIDID][SubValues]
 *                   Missing[UnknownSymbol, OSMRelationID][SubValues]
 *                   Missing[UnknownSymbol, PDBStructureID][SubValues]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][SubValues]
 *                   Missing[UnknownSymbol, PubChemCompoundID][SubValues]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][SubValues]
 *                   Missing[UnknownSymbol, PubMedCentralID][SubValues]
 *                   Missing[UnknownSymbol, PubMedID][SubValues]
 *                   Missing[UnknownSymbol, VIAFID][SubValues]
 * Sub values:       Missing[UnknownSymbol, WikidataID][SubValues]
 *
 *                   Missing[UnknownSymbol, ArXivID][DefaultValues]
 *                   Missing[UnknownSymbol, CASRegistryNumber][DefaultValues]
 *                   Missing[UnknownSymbol, ChEBIID][DefaultValues]
 *                   Missing[UnknownSymbol, ChEMBLID][DefaultValues]
 *                   Missing[UnknownSymbol, ChemSpiderID][DefaultValues]
 *                   Missing[UnknownSymbol, DOI][DefaultValues]
 *                   Missing[UnknownSymbol, DrugBankID][DefaultValues]
 *                   Missing[UnknownSymbol, GNDID][DefaultValues]
 *                   Missing[UnknownSymbol, InChI][DefaultValues]
 *                   Missing[UnknownSymbol, InChIKey][DefaultValues]
 *                   Missing[UnknownSymbol, ISAN][DefaultValues]
 *                   Missing[UnknownSymbol, ISBN10][DefaultValues]
 *                   Missing[UnknownSymbol, ISBN13][DefaultValues]
 *                   Missing[UnknownSymbol, ISMN][DefaultValues]
 *                   Missing[UnknownSymbol, ISNI][DefaultValues]
 *                   Missing[UnknownSymbol, ISRC][DefaultValues]
 *                   Missing[UnknownSymbol, ISSN][DefaultValues]
 *                   Missing[UnknownSymbol, ISWC][DefaultValues]
 *                   Missing[UnknownSymbol, KEGGID][DefaultValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][DefaultValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][DefaultValues]
 *                   Missing[UnknownSymbol, MeSHCode][DefaultValues]
 *                   Missing[UnknownSymbol, MeSHConceptID][DefaultValues]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][DefaultValues]
 *                   Missing[UnknownSymbol, MeSHTermID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][DefaultValues]
 *                   Missing[UnknownSymbol, OCLCControlNumber][DefaultValues]
 *                   Missing[UnknownSymbol, OCLCWorkID][DefaultValues]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][DefaultValues]
 *                   Missing[UnknownSymbol, ORCIDID][DefaultValues]
 *                   Missing[UnknownSymbol, OSMRelationID][DefaultValues]
 *                   Missing[UnknownSymbol, PDBStructureID][DefaultValues]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][DefaultValues]
 *                   Missing[UnknownSymbol, PubChemCompoundID][DefaultValues]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][DefaultValues]
 *                   Missing[UnknownSymbol, PubMedCentralID][DefaultValues]
 *                   Missing[UnknownSymbol, PubMedID][DefaultValues]
 *                   Missing[UnknownSymbol, VIAFID][DefaultValues]
 * Default value:    Missing[UnknownSymbol, WikidataID][DefaultValues]
 *
 *                   Missing[UnknownSymbol, ArXivID][NValues]
 *                   Missing[UnknownSymbol, CASRegistryNumber][NValues]
 *                   Missing[UnknownSymbol, ChEBIID][NValues]
 *                   Missing[UnknownSymbol, ChEMBLID][NValues]
 *                   Missing[UnknownSymbol, ChemSpiderID][NValues]
 *                   Missing[UnknownSymbol, DOI][NValues]
 *                   Missing[UnknownSymbol, DrugBankID][NValues]
 *                   Missing[UnknownSymbol, GNDID][NValues]
 *                   Missing[UnknownSymbol, InChI][NValues]
 *                   Missing[UnknownSymbol, InChIKey][NValues]
 *                   Missing[UnknownSymbol, ISAN][NValues]
 *                   Missing[UnknownSymbol, ISBN10][NValues]
 *                   Missing[UnknownSymbol, ISBN13][NValues]
 *                   Missing[UnknownSymbol, ISMN][NValues]
 *                   Missing[UnknownSymbol, ISNI][NValues]
 *                   Missing[UnknownSymbol, ISRC][NValues]
 *                   Missing[UnknownSymbol, ISSN][NValues]
 *                   Missing[UnknownSymbol, ISWC][NValues]
 *                   Missing[UnknownSymbol, KEGGID][NValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressAuthorityID][NValues]
 *                   Missing[UnknownSymbol, LibraryOfCongressControlNumber][NValues]
 *                   Missing[UnknownSymbol, MeSHCode][NValues]
 *                   Missing[UnknownSymbol, MeSHConceptID][NValues]
 *                   Missing[UnknownSymbol, MeSHDescriptorID][NValues]
 *                   Missing[UnknownSymbol, MeSHTermID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzAreaID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzArtistID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzEventID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzInstrumentID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzLabelID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzPlaceID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzRecordingID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseGroupID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzReleaseID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzSeriesID][NValues]
 *                   Missing[UnknownSymbol, MusicBrainzWorkID][NValues]
 *                   Missing[UnknownSymbol, OCLCControlNumber][NValues]
 *                   Missing[UnknownSymbol, OCLCWorkID][NValues]
 *                   Missing[UnknownSymbol, OpenCitationsBibliographicResourceID][NValues]
 *                   Missing[UnknownSymbol, ORCIDID][NValues]
 *                   Missing[UnknownSymbol, OSMRelationID][NValues]
 *                   Missing[UnknownSymbol, PDBStructureID][NValues]
 *                   Missing[UnknownSymbol, PubChemBioAssayID][NValues]
 *                   Missing[UnknownSymbol, PubChemCompoundID][NValues]
 *                   Missing[UnknownSymbol, PubChemSubstanceID][NValues]
 *                   Missing[UnknownSymbol, PubMedCentralID][NValues]
 *                   Missing[UnknownSymbol, PubMedID][NValues]
 *                   Missing[UnknownSymbol, VIAFID][NValues]
 * Numeric values:   Missing[UnknownSymbol, WikidataID][NValues]
 */
fun `$ExternalIdentifierTypes`(vararg arguments: Any?, options: MutableMap<String, Any?> = mutableMapOf()): MathematicaFunction {
	return MathematicaFunction("\$ExternalIdentifierTypes", arguments.toMutableList(), options)
}
