package com.daniloaraujosilva.mathemagika.library.jvm.common.generated

import com.daniloaraujosilva.mathemagika.library.jvm.common.MathematicaFunction

/**
 *````
 * 
 *                   ArXiv
 *                   BingSearch
 *                   ChemSpider
 *                   CrossRef
 *                   Dropbox
 *                   Facebook
 *                   Factual
 *                   FederalReserveEconomicData
 *                   Fitbit
 *                   Flickr
 *                   GoogleAnalytics
 *                   GoogleCalendar
 *                   GoogleContacts
 *                   GoogleCustomSearch
 *                   GooglePlus
 *                   GoogleTranslate
 *                   Instagram
 *                   IPFS
 *                   LinkedIn
 *                   MailChimp
 *                   MicrosoftTranslator
 *                   Mixpanel
 *                   MusicBrainz
 *                   OpenLibrary
 *                   OpenPHACTS
 *                   PubChem
 *                   PubMed
 *                   Pushbullet
 *                   Reddit
 *                   RunKeeper
 *                   SeatGeek
 *                   SurveyMonkey
 *                   Twilio
 *                   Twitter
 *                   Wikipedia
 * Name:             Yelp
 * 
 *                   Missing[UnknownSymbol, ArXiv][FullName]
 *                   Missing[UnknownSymbol, BingSearch][FullName]
 *                   Missing[UnknownSymbol, ChemSpider][FullName]
 *                   Missing[UnknownSymbol, CrossRef][FullName]
 *                   Missing[UnknownSymbol, Dropbox][FullName]
 *                   Missing[UnknownSymbol, Facebook][FullName]
 *                   Missing[UnknownSymbol, Factual][FullName]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][FullName]
 *                   Missing[UnknownSymbol, Fitbit][FullName]
 *                   Missing[UnknownSymbol, Flickr][FullName]
 *                   Missing[UnknownSymbol, GoogleAnalytics][FullName]
 *                   Missing[UnknownSymbol, GoogleCalendar][FullName]
 *                   Missing[UnknownSymbol, GoogleContacts][FullName]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][FullName]
 *                   Missing[UnknownSymbol, GooglePlus][FullName]
 *                   Missing[UnknownSymbol, GoogleTranslate][FullName]
 *                   Missing[UnknownSymbol, Instagram][FullName]
 *                   Missing[UnknownSymbol, IPFS][FullName]
 *                   Missing[UnknownSymbol, LinkedIn][FullName]
 *                   Missing[UnknownSymbol, MailChimp][FullName]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][FullName]
 *                   Missing[UnknownSymbol, Mixpanel][FullName]
 *                   Missing[UnknownSymbol, MusicBrainz][FullName]
 *                   Missing[UnknownSymbol, OpenLibrary][FullName]
 *                   Missing[UnknownSymbol, OpenPHACTS][FullName]
 *                   Missing[UnknownSymbol, PubChem][FullName]
 *                   Missing[UnknownSymbol, PubMed][FullName]
 *                   Missing[UnknownSymbol, Pushbullet][FullName]
 *                   Missing[UnknownSymbol, Reddit][FullName]
 *                   Missing[UnknownSymbol, RunKeeper][FullName]
 *                   Missing[UnknownSymbol, SeatGeek][FullName]
 *                   Missing[UnknownSymbol, SurveyMonkey][FullName]
 *                   Missing[UnknownSymbol, Twilio][FullName]
 *                   Missing[UnknownSymbol, Twitter][FullName]
 *                   Missing[UnknownSymbol, Wikipedia][FullName]
 * Full name:        Missing[UnknownSymbol, Yelp][FullName]
 * 
 * Usage:            {Missing[UnknownSymbol, ArXiv][Usage], Missing[UnknownSymbol, BingSearch][Usage], Missing[UnknownSymbol, ChemSpider][Usage], Missing[UnknownSymbol, CrossRef][Usage], Missing[UnknownSymbol, Dropbox][Usage], Missing[UnknownSymbol, Facebook][Usage], Missing[UnknownSymbol, Factual][Usage], Missing[UnknownSymbol, FederalReserveEconomicData][Usage], Missing[UnknownSymbol, Fitbit][Usage], Missing[UnknownSymbol, Flickr][Usage], Missing[UnknownSymbol, GoogleAnalytics][Usage], Missing[UnknownSymbol, GoogleCalendar][Usage], Missing[UnknownSymbol, GoogleContacts][Usage], Missing[UnknownSymbol, GoogleCustomSearch][Usage], Missing[UnknownSymbol, GooglePlus][Usage], Missing[UnknownSymbol, GoogleTranslate][Usage], Missing[UnknownSymbol, Instagram][Usage], Missing[UnknownSymbol, IPFS][Usage], Missing[UnknownSymbol, LinkedIn][Usage], Missing[UnknownSymbol, MailChimp][Usage], Missing[UnknownSymbol, MicrosoftTranslator][Usage], Missing[UnknownSymbol, Mixpanel][Usage], Missing[UnknownSymbol, MusicBrainz][Usage], Missing[UnknownSymbol, OpenLibrary][Usage], Missing[UnknownSymbol, OpenPHACTS][Usage], Missing[UnknownSymbol, PubChem][Usage], Missing[UnknownSymbol, PubMed][Usage], Missing[UnknownSymbol, Pushbullet][Usage], Missing[UnknownSymbol, Reddit][Usage], Missing[UnknownSymbol, RunKeeper][Usage], Missing[UnknownSymbol, SeatGeek][Usage], Missing[UnknownSymbol, SurveyMonkey][Usage], Missing[UnknownSymbol, Twilio][Usage], Missing[UnknownSymbol, Twitter][Usage], Missing[UnknownSymbol, Wikipedia][Usage], Missing[UnknownSymbol, Yelp][Usage]}
 * 
 *                   Missing[UnknownSymbol, ArXiv][Options]
 *                   Missing[UnknownSymbol, BingSearch][Options]
 *                   Missing[UnknownSymbol, ChemSpider][Options]
 *                   Missing[UnknownSymbol, CrossRef][Options]
 *                   Missing[UnknownSymbol, Dropbox][Options]
 *                   Missing[UnknownSymbol, Facebook][Options]
 *                   Missing[UnknownSymbol, Factual][Options]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][Options]
 *                   Missing[UnknownSymbol, Fitbit][Options]
 *                   Missing[UnknownSymbol, Flickr][Options]
 *                   Missing[UnknownSymbol, GoogleAnalytics][Options]
 *                   Missing[UnknownSymbol, GoogleCalendar][Options]
 *                   Missing[UnknownSymbol, GoogleContacts][Options]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][Options]
 *                   Missing[UnknownSymbol, GooglePlus][Options]
 *                   Missing[UnknownSymbol, GoogleTranslate][Options]
 *                   Missing[UnknownSymbol, Instagram][Options]
 *                   Missing[UnknownSymbol, IPFS][Options]
 *                   Missing[UnknownSymbol, LinkedIn][Options]
 *                   Missing[UnknownSymbol, MailChimp][Options]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][Options]
 *                   Missing[UnknownSymbol, Mixpanel][Options]
 *                   Missing[UnknownSymbol, MusicBrainz][Options]
 *                   Missing[UnknownSymbol, OpenLibrary][Options]
 *                   Missing[UnknownSymbol, OpenPHACTS][Options]
 *                   Missing[UnknownSymbol, PubChem][Options]
 *                   Missing[UnknownSymbol, PubMed][Options]
 *                   Missing[UnknownSymbol, Pushbullet][Options]
 *                   Missing[UnknownSymbol, Reddit][Options]
 *                   Missing[UnknownSymbol, RunKeeper][Options]
 *                   Missing[UnknownSymbol, SeatGeek][Options]
 *                   Missing[UnknownSymbol, SurveyMonkey][Options]
 *                   Missing[UnknownSymbol, Twilio][Options]
 *                   Missing[UnknownSymbol, Twitter][Options]
 *                   Missing[UnknownSymbol, Wikipedia][Options]
 * Options:          Missing[UnknownSymbol, Yelp][Options]
 * 
 *                   Missing[UnknownSymbol, ArXiv][Attributes]
 *                   Missing[UnknownSymbol, BingSearch][Attributes]
 *                   Missing[UnknownSymbol, ChemSpider][Attributes]
 *                   Missing[UnknownSymbol, CrossRef][Attributes]
 *                   Missing[UnknownSymbol, Dropbox][Attributes]
 *                   Missing[UnknownSymbol, Facebook][Attributes]
 *                   Missing[UnknownSymbol, Factual][Attributes]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][Attributes]
 *                   Missing[UnknownSymbol, Fitbit][Attributes]
 *                   Missing[UnknownSymbol, Flickr][Attributes]
 *                   Missing[UnknownSymbol, GoogleAnalytics][Attributes]
 *                   Missing[UnknownSymbol, GoogleCalendar][Attributes]
 *                   Missing[UnknownSymbol, GoogleContacts][Attributes]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][Attributes]
 *                   Missing[UnknownSymbol, GooglePlus][Attributes]
 *                   Missing[UnknownSymbol, GoogleTranslate][Attributes]
 *                   Missing[UnknownSymbol, Instagram][Attributes]
 *                   Missing[UnknownSymbol, IPFS][Attributes]
 *                   Missing[UnknownSymbol, LinkedIn][Attributes]
 *                   Missing[UnknownSymbol, MailChimp][Attributes]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][Attributes]
 *                   Missing[UnknownSymbol, Mixpanel][Attributes]
 *                   Missing[UnknownSymbol, MusicBrainz][Attributes]
 *                   Missing[UnknownSymbol, OpenLibrary][Attributes]
 *                   Missing[UnknownSymbol, OpenPHACTS][Attributes]
 *                   Missing[UnknownSymbol, PubChem][Attributes]
 *                   Missing[UnknownSymbol, PubMed][Attributes]
 *                   Missing[UnknownSymbol, Pushbullet][Attributes]
 *                   Missing[UnknownSymbol, Reddit][Attributes]
 *                   Missing[UnknownSymbol, RunKeeper][Attributes]
 *                   Missing[UnknownSymbol, SeatGeek][Attributes]
 *                   Missing[UnknownSymbol, SurveyMonkey][Attributes]
 *                   Missing[UnknownSymbol, Twilio][Attributes]
 *                   Missing[UnknownSymbol, Twitter][Attributes]
 *                   Missing[UnknownSymbol, Wikipedia][Attributes]
 * Attributes:       Missing[UnknownSymbol, Yelp][Attributes]
 * 
 *                   local: <>{Missing[UnknownSymbol, ArXiv][Documentation], Missing[UnknownSymbol, BingSearch][Documentation], Missing[UnknownSymbol, ChemSpider][Documentation], Missing[UnknownSymbol, CrossRef][Documentation], Missing[UnknownSymbol, Dropbox][Documentation], Missing[UnknownSymbol, Facebook][Documentation], Missing[UnknownSymbol, Factual][Documentation], Missing[UnknownSymbol, FederalReserveEconomicData][Documentation], Missing[UnknownSymbol, Fitbit][Documentation], Missing[UnknownSymbol, Flickr][Documentation], Missing[UnknownSymbol, GoogleAnalytics][Documentation], Missing[UnknownSymbol, GoogleCalendar][Documentation], Missing[UnknownSymbol, GoogleContacts][Documentation], Missing[UnknownSymbol, GoogleCustomSearch][Documentation], Missing[UnknownSymbol, GooglePlus][Documentation], Missing[UnknownSymbol, GoogleTranslate][Documentation], Missing[UnknownSymbol, Instagram][Documentation], Missing[UnknownSymbol, IPFS][Documentation], Missing[UnknownSymbol, LinkedIn][Documentation], Missing[UnknownSymbol, MailChimp][Documentation], Missing[UnknownSymbol, MicrosoftTranslator][Documentation], Missing[UnknownSymbol, Mixpanel][Documentation], Missing[UnknownSymbol, MusicBrainz][Documentation], Missing[UnknownSymbol, OpenLibrary][Documentation], Missing[UnknownSymbol, OpenPHACTS][Documentation], Missing[UnknownSymbol, PubChem][Documentation], Missing[UnknownSymbol, PubMed][Documentation], Missing[UnknownSymbol, Pushbullet][Documentation], Missing[UnknownSymbol, Reddit][Documentation], Missing[UnknownSymbol, RunKeeper][Documentation], Missing[UnknownSymbol, SeatGeek][Documentation], Missing[UnknownSymbol, SurveyMonkey][Documentation], Missing[UnknownSymbol, Twilio][Documentation], Missing[UnknownSymbol, Twitter][Documentation], Missing[UnknownSymbol, Wikipedia][Documentation], Missing[UnknownSymbol, Yelp][Documentation]}[Local]
 * Documentation:    web: <>{Missing[UnknownSymbol, ArXiv][Documentation], Missing[UnknownSymbol, BingSearch][Documentation], Missing[UnknownSymbol, ChemSpider][Documentation], Missing[UnknownSymbol, CrossRef][Documentation], Missing[UnknownSymbol, Dropbox][Documentation], Missing[UnknownSymbol, Facebook][Documentation], Missing[UnknownSymbol, Factual][Documentation], Missing[UnknownSymbol, FederalReserveEconomicData][Documentation], Missing[UnknownSymbol, Fitbit][Documentation], Missing[UnknownSymbol, Flickr][Documentation], Missing[UnknownSymbol, GoogleAnalytics][Documentation], Missing[UnknownSymbol, GoogleCalendar][Documentation], Missing[UnknownSymbol, GoogleContacts][Documentation], Missing[UnknownSymbol, GoogleCustomSearch][Documentation], Missing[UnknownSymbol, GooglePlus][Documentation], Missing[UnknownSymbol, GoogleTranslate][Documentation], Missing[UnknownSymbol, Instagram][Documentation], Missing[UnknownSymbol, IPFS][Documentation], Missing[UnknownSymbol, LinkedIn][Documentation], Missing[UnknownSymbol, MailChimp][Documentation], Missing[UnknownSymbol, MicrosoftTranslator][Documentation], Missing[UnknownSymbol, Mixpanel][Documentation], Missing[UnknownSymbol, MusicBrainz][Documentation], Missing[UnknownSymbol, OpenLibrary][Documentation], Missing[UnknownSymbol, OpenPHACTS][Documentation], Missing[UnknownSymbol, PubChem][Documentation], Missing[UnknownSymbol, PubMed][Documentation], Missing[UnknownSymbol, Pushbullet][Documentation], Missing[UnknownSymbol, Reddit][Documentation], Missing[UnknownSymbol, RunKeeper][Documentation], Missing[UnknownSymbol, SeatGeek][Documentation], Missing[UnknownSymbol, SurveyMonkey][Documentation], Missing[UnknownSymbol, Twilio][Documentation], Missing[UnknownSymbol, Twitter][Documentation], Missing[UnknownSymbol, Wikipedia][Documentation], Missing[UnknownSymbol, Yelp][Documentation]}[Web]
 * 
 *                   Missing[UnknownSymbol, ArXiv][Definitions]
 *                   Missing[UnknownSymbol, BingSearch][Definitions]
 *                   Missing[UnknownSymbol, ChemSpider][Definitions]
 *                   Missing[UnknownSymbol, CrossRef][Definitions]
 *                   Missing[UnknownSymbol, Dropbox][Definitions]
 *                   Missing[UnknownSymbol, Facebook][Definitions]
 *                   Missing[UnknownSymbol, Factual][Definitions]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][Definitions]
 *                   Missing[UnknownSymbol, Fitbit][Definitions]
 *                   Missing[UnknownSymbol, Flickr][Definitions]
 *                   Missing[UnknownSymbol, GoogleAnalytics][Definitions]
 *                   Missing[UnknownSymbol, GoogleCalendar][Definitions]
 *                   Missing[UnknownSymbol, GoogleContacts][Definitions]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][Definitions]
 *                   Missing[UnknownSymbol, GooglePlus][Definitions]
 *                   Missing[UnknownSymbol, GoogleTranslate][Definitions]
 *                   Missing[UnknownSymbol, Instagram][Definitions]
 *                   Missing[UnknownSymbol, IPFS][Definitions]
 *                   Missing[UnknownSymbol, LinkedIn][Definitions]
 *                   Missing[UnknownSymbol, MailChimp][Definitions]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][Definitions]
 *                   Missing[UnknownSymbol, Mixpanel][Definitions]
 *                   Missing[UnknownSymbol, MusicBrainz][Definitions]
 *                   Missing[UnknownSymbol, OpenLibrary][Definitions]
 *                   Missing[UnknownSymbol, OpenPHACTS][Definitions]
 *                   Missing[UnknownSymbol, PubChem][Definitions]
 *                   Missing[UnknownSymbol, PubMed][Definitions]
 *                   Missing[UnknownSymbol, Pushbullet][Definitions]
 *                   Missing[UnknownSymbol, Reddit][Definitions]
 *                   Missing[UnknownSymbol, RunKeeper][Definitions]
 *                   Missing[UnknownSymbol, SeatGeek][Definitions]
 *                   Missing[UnknownSymbol, SurveyMonkey][Definitions]
 *                   Missing[UnknownSymbol, Twilio][Definitions]
 *                   Missing[UnknownSymbol, Twitter][Definitions]
 *                   Missing[UnknownSymbol, Wikipedia][Definitions]
 * Definitions:      Missing[UnknownSymbol, Yelp][Definitions]
 * 
 *                   Missing[UnknownSymbol, ArXiv][OwnValues]
 *                   Missing[UnknownSymbol, BingSearch][OwnValues]
 *                   Missing[UnknownSymbol, ChemSpider][OwnValues]
 *                   Missing[UnknownSymbol, CrossRef][OwnValues]
 *                   Missing[UnknownSymbol, Dropbox][OwnValues]
 *                   Missing[UnknownSymbol, Facebook][OwnValues]
 *                   Missing[UnknownSymbol, Factual][OwnValues]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][OwnValues]
 *                   Missing[UnknownSymbol, Fitbit][OwnValues]
 *                   Missing[UnknownSymbol, Flickr][OwnValues]
 *                   Missing[UnknownSymbol, GoogleAnalytics][OwnValues]
 *                   Missing[UnknownSymbol, GoogleCalendar][OwnValues]
 *                   Missing[UnknownSymbol, GoogleContacts][OwnValues]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][OwnValues]
 *                   Missing[UnknownSymbol, GooglePlus][OwnValues]
 *                   Missing[UnknownSymbol, GoogleTranslate][OwnValues]
 *                   Missing[UnknownSymbol, Instagram][OwnValues]
 *                   Missing[UnknownSymbol, IPFS][OwnValues]
 *                   Missing[UnknownSymbol, LinkedIn][OwnValues]
 *                   Missing[UnknownSymbol, MailChimp][OwnValues]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][OwnValues]
 *                   Missing[UnknownSymbol, Mixpanel][OwnValues]
 *                   Missing[UnknownSymbol, MusicBrainz][OwnValues]
 *                   Missing[UnknownSymbol, OpenLibrary][OwnValues]
 *                   Missing[UnknownSymbol, OpenPHACTS][OwnValues]
 *                   Missing[UnknownSymbol, PubChem][OwnValues]
 *                   Missing[UnknownSymbol, PubMed][OwnValues]
 *                   Missing[UnknownSymbol, Pushbullet][OwnValues]
 *                   Missing[UnknownSymbol, Reddit][OwnValues]
 *                   Missing[UnknownSymbol, RunKeeper][OwnValues]
 *                   Missing[UnknownSymbol, SeatGeek][OwnValues]
 *                   Missing[UnknownSymbol, SurveyMonkey][OwnValues]
 *                   Missing[UnknownSymbol, Twilio][OwnValues]
 *                   Missing[UnknownSymbol, Twitter][OwnValues]
 *                   Missing[UnknownSymbol, Wikipedia][OwnValues]
 * Own values:       Missing[UnknownSymbol, Yelp][OwnValues]
 * 
 *                   Missing[UnknownSymbol, ArXiv][DownValues]
 *                   Missing[UnknownSymbol, BingSearch][DownValues]
 *                   Missing[UnknownSymbol, ChemSpider][DownValues]
 *                   Missing[UnknownSymbol, CrossRef][DownValues]
 *                   Missing[UnknownSymbol, Dropbox][DownValues]
 *                   Missing[UnknownSymbol, Facebook][DownValues]
 *                   Missing[UnknownSymbol, Factual][DownValues]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][DownValues]
 *                   Missing[UnknownSymbol, Fitbit][DownValues]
 *                   Missing[UnknownSymbol, Flickr][DownValues]
 *                   Missing[UnknownSymbol, GoogleAnalytics][DownValues]
 *                   Missing[UnknownSymbol, GoogleCalendar][DownValues]
 *                   Missing[UnknownSymbol, GoogleContacts][DownValues]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][DownValues]
 *                   Missing[UnknownSymbol, GooglePlus][DownValues]
 *                   Missing[UnknownSymbol, GoogleTranslate][DownValues]
 *                   Missing[UnknownSymbol, Instagram][DownValues]
 *                   Missing[UnknownSymbol, IPFS][DownValues]
 *                   Missing[UnknownSymbol, LinkedIn][DownValues]
 *                   Missing[UnknownSymbol, MailChimp][DownValues]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][DownValues]
 *                   Missing[UnknownSymbol, Mixpanel][DownValues]
 *                   Missing[UnknownSymbol, MusicBrainz][DownValues]
 *                   Missing[UnknownSymbol, OpenLibrary][DownValues]
 *                   Missing[UnknownSymbol, OpenPHACTS][DownValues]
 *                   Missing[UnknownSymbol, PubChem][DownValues]
 *                   Missing[UnknownSymbol, PubMed][DownValues]
 *                   Missing[UnknownSymbol, Pushbullet][DownValues]
 *                   Missing[UnknownSymbol, Reddit][DownValues]
 *                   Missing[UnknownSymbol, RunKeeper][DownValues]
 *                   Missing[UnknownSymbol, SeatGeek][DownValues]
 *                   Missing[UnknownSymbol, SurveyMonkey][DownValues]
 *                   Missing[UnknownSymbol, Twilio][DownValues]
 *                   Missing[UnknownSymbol, Twitter][DownValues]
 *                   Missing[UnknownSymbol, Wikipedia][DownValues]
 * Down values:      Missing[UnknownSymbol, Yelp][DownValues]
 * 
 *                   Missing[UnknownSymbol, ArXiv][UpValues]
 *                   Missing[UnknownSymbol, BingSearch][UpValues]
 *                   Missing[UnknownSymbol, ChemSpider][UpValues]
 *                   Missing[UnknownSymbol, CrossRef][UpValues]
 *                   Missing[UnknownSymbol, Dropbox][UpValues]
 *                   Missing[UnknownSymbol, Facebook][UpValues]
 *                   Missing[UnknownSymbol, Factual][UpValues]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][UpValues]
 *                   Missing[UnknownSymbol, Fitbit][UpValues]
 *                   Missing[UnknownSymbol, Flickr][UpValues]
 *                   Missing[UnknownSymbol, GoogleAnalytics][UpValues]
 *                   Missing[UnknownSymbol, GoogleCalendar][UpValues]
 *                   Missing[UnknownSymbol, GoogleContacts][UpValues]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][UpValues]
 *                   Missing[UnknownSymbol, GooglePlus][UpValues]
 *                   Missing[UnknownSymbol, GoogleTranslate][UpValues]
 *                   Missing[UnknownSymbol, Instagram][UpValues]
 *                   Missing[UnknownSymbol, IPFS][UpValues]
 *                   Missing[UnknownSymbol, LinkedIn][UpValues]
 *                   Missing[UnknownSymbol, MailChimp][UpValues]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][UpValues]
 *                   Missing[UnknownSymbol, Mixpanel][UpValues]
 *                   Missing[UnknownSymbol, MusicBrainz][UpValues]
 *                   Missing[UnknownSymbol, OpenLibrary][UpValues]
 *                   Missing[UnknownSymbol, OpenPHACTS][UpValues]
 *                   Missing[UnknownSymbol, PubChem][UpValues]
 *                   Missing[UnknownSymbol, PubMed][UpValues]
 *                   Missing[UnknownSymbol, Pushbullet][UpValues]
 *                   Missing[UnknownSymbol, Reddit][UpValues]
 *                   Missing[UnknownSymbol, RunKeeper][UpValues]
 *                   Missing[UnknownSymbol, SeatGeek][UpValues]
 *                   Missing[UnknownSymbol, SurveyMonkey][UpValues]
 *                   Missing[UnknownSymbol, Twilio][UpValues]
 *                   Missing[UnknownSymbol, Twitter][UpValues]
 *                   Missing[UnknownSymbol, Wikipedia][UpValues]
 * Up values:        Missing[UnknownSymbol, Yelp][UpValues]
 * 
 *                   Missing[UnknownSymbol, ArXiv][SubValues]
 *                   Missing[UnknownSymbol, BingSearch][SubValues]
 *                   Missing[UnknownSymbol, ChemSpider][SubValues]
 *                   Missing[UnknownSymbol, CrossRef][SubValues]
 *                   Missing[UnknownSymbol, Dropbox][SubValues]
 *                   Missing[UnknownSymbol, Facebook][SubValues]
 *                   Missing[UnknownSymbol, Factual][SubValues]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][SubValues]
 *                   Missing[UnknownSymbol, Fitbit][SubValues]
 *                   Missing[UnknownSymbol, Flickr][SubValues]
 *                   Missing[UnknownSymbol, GoogleAnalytics][SubValues]
 *                   Missing[UnknownSymbol, GoogleCalendar][SubValues]
 *                   Missing[UnknownSymbol, GoogleContacts][SubValues]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][SubValues]
 *                   Missing[UnknownSymbol, GooglePlus][SubValues]
 *                   Missing[UnknownSymbol, GoogleTranslate][SubValues]
 *                   Missing[UnknownSymbol, Instagram][SubValues]
 *                   Missing[UnknownSymbol, IPFS][SubValues]
 *                   Missing[UnknownSymbol, LinkedIn][SubValues]
 *                   Missing[UnknownSymbol, MailChimp][SubValues]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][SubValues]
 *                   Missing[UnknownSymbol, Mixpanel][SubValues]
 *                   Missing[UnknownSymbol, MusicBrainz][SubValues]
 *                   Missing[UnknownSymbol, OpenLibrary][SubValues]
 *                   Missing[UnknownSymbol, OpenPHACTS][SubValues]
 *                   Missing[UnknownSymbol, PubChem][SubValues]
 *                   Missing[UnknownSymbol, PubMed][SubValues]
 *                   Missing[UnknownSymbol, Pushbullet][SubValues]
 *                   Missing[UnknownSymbol, Reddit][SubValues]
 *                   Missing[UnknownSymbol, RunKeeper][SubValues]
 *                   Missing[UnknownSymbol, SeatGeek][SubValues]
 *                   Missing[UnknownSymbol, SurveyMonkey][SubValues]
 *                   Missing[UnknownSymbol, Twilio][SubValues]
 *                   Missing[UnknownSymbol, Twitter][SubValues]
 *                   Missing[UnknownSymbol, Wikipedia][SubValues]
 * Sub values:       Missing[UnknownSymbol, Yelp][SubValues]
 * 
 *                   Missing[UnknownSymbol, ArXiv][DefaultValues]
 *                   Missing[UnknownSymbol, BingSearch][DefaultValues]
 *                   Missing[UnknownSymbol, ChemSpider][DefaultValues]
 *                   Missing[UnknownSymbol, CrossRef][DefaultValues]
 *                   Missing[UnknownSymbol, Dropbox][DefaultValues]
 *                   Missing[UnknownSymbol, Facebook][DefaultValues]
 *                   Missing[UnknownSymbol, Factual][DefaultValues]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][DefaultValues]
 *                   Missing[UnknownSymbol, Fitbit][DefaultValues]
 *                   Missing[UnknownSymbol, Flickr][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleAnalytics][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleCalendar][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleContacts][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][DefaultValues]
 *                   Missing[UnknownSymbol, GooglePlus][DefaultValues]
 *                   Missing[UnknownSymbol, GoogleTranslate][DefaultValues]
 *                   Missing[UnknownSymbol, Instagram][DefaultValues]
 *                   Missing[UnknownSymbol, IPFS][DefaultValues]
 *                   Missing[UnknownSymbol, LinkedIn][DefaultValues]
 *                   Missing[UnknownSymbol, MailChimp][DefaultValues]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][DefaultValues]
 *                   Missing[UnknownSymbol, Mixpanel][DefaultValues]
 *                   Missing[UnknownSymbol, MusicBrainz][DefaultValues]
 *                   Missing[UnknownSymbol, OpenLibrary][DefaultValues]
 *                   Missing[UnknownSymbol, OpenPHACTS][DefaultValues]
 *                   Missing[UnknownSymbol, PubChem][DefaultValues]
 *                   Missing[UnknownSymbol, PubMed][DefaultValues]
 *                   Missing[UnknownSymbol, Pushbullet][DefaultValues]
 *                   Missing[UnknownSymbol, Reddit][DefaultValues]
 *                   Missing[UnknownSymbol, RunKeeper][DefaultValues]
 *                   Missing[UnknownSymbol, SeatGeek][DefaultValues]
 *                   Missing[UnknownSymbol, SurveyMonkey][DefaultValues]
 *                   Missing[UnknownSymbol, Twilio][DefaultValues]
 *                   Missing[UnknownSymbol, Twitter][DefaultValues]
 *                   Missing[UnknownSymbol, Wikipedia][DefaultValues]
 * Default value:    Missing[UnknownSymbol, Yelp][DefaultValues]
 * 
 *                   Missing[UnknownSymbol, ArXiv][NValues]
 *                   Missing[UnknownSymbol, BingSearch][NValues]
 *                   Missing[UnknownSymbol, ChemSpider][NValues]
 *                   Missing[UnknownSymbol, CrossRef][NValues]
 *                   Missing[UnknownSymbol, Dropbox][NValues]
 *                   Missing[UnknownSymbol, Facebook][NValues]
 *                   Missing[UnknownSymbol, Factual][NValues]
 *                   Missing[UnknownSymbol, FederalReserveEconomicData][NValues]
 *                   Missing[UnknownSymbol, Fitbit][NValues]
 *                   Missing[UnknownSymbol, Flickr][NValues]
 *                   Missing[UnknownSymbol, GoogleAnalytics][NValues]
 *                   Missing[UnknownSymbol, GoogleCalendar][NValues]
 *                   Missing[UnknownSymbol, GoogleContacts][NValues]
 *                   Missing[UnknownSymbol, GoogleCustomSearch][NValues]
 *                   Missing[UnknownSymbol, GooglePlus][NValues]
 *                   Missing[UnknownSymbol, GoogleTranslate][NValues]
 *                   Missing[UnknownSymbol, Instagram][NValues]
 *                   Missing[UnknownSymbol, IPFS][NValues]
 *                   Missing[UnknownSymbol, LinkedIn][NValues]
 *                   Missing[UnknownSymbol, MailChimp][NValues]
 *                   Missing[UnknownSymbol, MicrosoftTranslator][NValues]
 *                   Missing[UnknownSymbol, Mixpanel][NValues]
 *                   Missing[UnknownSymbol, MusicBrainz][NValues]
 *                   Missing[UnknownSymbol, OpenLibrary][NValues]
 *                   Missing[UnknownSymbol, OpenPHACTS][NValues]
 *                   Missing[UnknownSymbol, PubChem][NValues]
 *                   Missing[UnknownSymbol, PubMed][NValues]
 *                   Missing[UnknownSymbol, Pushbullet][NValues]
 *                   Missing[UnknownSymbol, Reddit][NValues]
 *                   Missing[UnknownSymbol, RunKeeper][NValues]
 *                   Missing[UnknownSymbol, SeatGeek][NValues]
 *                   Missing[UnknownSymbol, SurveyMonkey][NValues]
 *                   Missing[UnknownSymbol, Twilio][NValues]
 *                   Missing[UnknownSymbol, Twitter][NValues]
 *                   Missing[UnknownSymbol, Wikipedia][NValues]
 * Numeric values:   Missing[UnknownSymbol, Yelp][NValues]
 */
fun `$Services`(vararg arguments: Any?, options: MutableMap<String, Any?> = mutableMapOf()): MathematicaFunction {
	return MathematicaFunction("\$Services", arguments.toMutableList(), options)
}
