package com.daniloaraujosilva.mathemagika.library.jvm.functions

import com.daniloaraujosilva.mathemagika.library.jvm.common.MathematicaFunction

/**
 *````
 *
 * Name:             <|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>
 *
 * Full name:        Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, FullName]
 *
 * Usage:            Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, Usage]
 *
 * Options:          Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, Options]
 *
 * Attributes:       Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, Attributes]
 *
 *                   local: <>Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, Documentation][Local]
 * Documentation:    web: <>Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, Documentation][Web]
 *
 * Definitions:      Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, Definitions]
 *
 * Own values:       Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, OwnValues]
 *
 * Down values:      Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, DownValues]
 *
 * Up values:        Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, UpValues]
 *
 * Sub values:       Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, SubValues]
 *
 * Default value:    Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, DefaultValues]
 *
 * Numeric values:   Information[<|Matroska -> {{ASS, ASS (Advanced SubStation Alpha) subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {SUBRIP, SubRip subtitle}, {TEXT, Raw text subtitle}, {WEBVTT, WebVTT subtitle}}, MP4 -> {{MOV-TEXT, 3GPP Timed Text subtitle}}, QuickTime -> {{CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {MOV-TEXT, 3GPP Timed Text subtitle}}, VideoFormat -> {{3GTEXT-AVF, 3GText AVFoundation decoder}, {ASS, ASS (Advanced SubStation Alpha) subtitle}, {CC-DEC, Closed Caption (EIA-608 / CEA-708)}, {DVBSUB, DVB subtitles}, {DVDSUB, DVD subtitles}, {JACOSUB, JACOsub subtitle}, {MICRODVD, MicroDVD subtitle}, {MOV-TEXT, 3GPP Timed Text subtitle}, {MPL2, MPL2 subtitle}, {PGSSUB, HDMV Presentation Graphic Stream subtitles}, {PJS, PJS subtitle}, {REALTEXT, RealText subtitle}, {SAMI, SAMI subtitle}, {SRT, SubRip subtitle}, {SSA, ASS (Advanced SubStation Alpha) subtitle}, {STL, Spruce subtitle format}, {SUBRIP, SubRip subtitle}, {SUBVIEWER, SubViewer subtitle}, {SUBVIEWER1, SubViewer1 subtitle}, {TEXT, Raw text subtitle}, {VPLAYER, VPlayer subtitle}, {WEBVTT, WebVTT subtitle}, {WEBVTT-AVF, WebVTT AVFoundation decoder}, {XSUB, XSUB}}|>, NValues]
 */
fun `$SubtitleDecoders`(vararg arguments: Any?, options: MutableMap<String, Any?> = mutableMapOf()): MathematicaFunction {
	return MathematicaFunction("\$SubtitleDecoders", arguments.toMutableList(), options)
}
